### ISSUE TITLE
How do you implement such tabs in this image?

### ISSUE THREAD

**Issue by JeffreyCA** [codepath/android_guides#100]
![Image of Fragment Tabs](https://camo.githubusercontent.com/7c5e4d1319786ce2020b8d4b7d4a832408187bf5/68747470733a2f2f692e696d6775722e636f6d2f37357a716e784e2e706e67)

**Comment by nesquena** [comment]
See https://guides.codepath.com/android/ViewPager-with-FragmentPagerAdapter#usage (PagerTabStrip) to add that. It's called a viewpager indicator.
