### ISSUE TITLE
Retrofit 2.0

### ISSUE THREAD

**Issue by nesquena** [codepath/android_guides#102]
http://inthecheesefactory.com/blog/retrofit-2.0/

Upgrade our Retrofit guide to 2.0 /cc @rogerhu

**Comment by zeeshanaslam78** [comment]
Very helpful post

**Comment by rogerhu** [comment]
Updated here: https://github.com/codepath/android_guides/wiki/Consuming-APIs-with-Retrofit

**Comment by rogerhu** [comment]
Let me know if you have any thoughts!

**Comment by nesquena** [comment]
Nice! Thanks for putting that together

**Comment by ayon115** [comment]
I have written a tutorial few days ago. 
http://www.iayon.com/consuming-rest-api-with-retrofit-2-0-in-android/

**Comment by Devofure** [comment]
here is another tutorial i found in the internet about  retrofit 2.0 with rxjava compatibility 
http://inthecheesefactory.com/blog/retrofit-2.0/en

**Comment by nesquena** [comment]
@rogerhu Should this be closed or should we wait for 2.0 release?
