### ISSUE TITLE
Explicitly defined default constructor in EditNameDialog

### ISSUE THREAD

**Issue by farmazon3000** [codepath/android_guides#103]
In [Using DialogFragment](https://github.com/codepath/android_guides/wiki/Using-DialogFragment)
there is

```
public EditNameDialog() {
  // Empty constructor required for DialogFragment
}
```

I think this declaration is redundant and is misleading. [Java docs about "Providing Constructors for Your Classes"](https://docs.oracle.com/javase/tutorial/java/javaOO/constructors.html) says:

> The compiler automatically provides a no-argument, default constructor for any class without constructors.

The class `EditNameDialog` would define the `public EditNameDialog()` automatically so defining it explicitly is bad practice and should be removed.

**Comment by nesquena** [comment]
You are right, it's a warning to make sure people don't override the default constructor by accident. Note the same warning / note is here http://android-developers.blogspot.com/2012/05/using-dialogfragments.html in the official introduction of the dialog fragment by google. Also see here http://stackoverflow.com/questions/10450348/do-fragments-really-need-an-empty-constructor and in [many books](https://books.google.com/books?id=iO5pX6WoK8YC&pg=PA94&lpg=PA94&dq=dialogfragment+require+empty+constructor&source=bl&ots=0kERsT7scB&sig=r8WXGZKMaTnOSFh9nVH2Tr9ikAc&hl=en&sa=X&ved=0CCYQ6AEwATgUahUKEwjQxNnPmvbHAhXLLIgKHVDuAC0#v=onepage&q=dialogfragment%20require%20empty%20constructor&f=false).

**Comment by farmazon3000** [comment]
The reason why people ask this http://stackoverflow.com/questions/10450348/do-fragments-really-need-an-empty-constructor question a lot is exactly because other people add things like that

```
public EditNameDialog() {
  // Empty constructor required for DialogFragment
}
```

which is misleading. Fact that it's so commonly repeated does not licence you to repeat it again.
