### ISSUE TITLE
RequestInterceptor Retrofit 2.0 Tutorial

### ISSUE THREAD

**Issue by MehdiChouag** [codepath/android_guides#106]
Hi, everyone

On the Retrofit 2.0 tutorial, which is very interesting by the way, there is an error in the section about  OAuth. The class RequestInterceptor was removed, now we have to use the Interceptor class of OkHttp instead.

**Comment by rogerhu** [comment]
Great, thanks for the catch.  Have fixed.  Can you reverify?
