### ISSUE TITLE
recyclerview with database 

### ISSUE THREAD

**Issue by aoiserizawa** [codepath/android_guides#107]
hey guys I need help for a tutorial on how to communicate recyclerview with sqlite database. currently what Im using is this http://stackoverflow.com/questions/33095691/recyclerview-with-sqlite-the-right-way?noredirect=1#comment54007847_33095691. They gave their answers but I need a complete tutorial for recyclerview with access to database for a noob like me. Even just a simple complete example on how to get data from the database and put it in recyclerview would do. I hope someone help me with this. Thanks In Advance

**Comment by nesquena** [comment]
@aoiserizawa can you try copying this and using it in your app https://gist.github.com/skyfishjy/443b7448f59be978bc59. Do you know how to get the cursor for the data you want to display? Refer to [SQL Guide](http://guides.codepath.com/android/Local-Databases-with-SQLiteOpenHelper#querying-records) for information on that.

Please reply back if you get it working.

**Comment by aoiserizawa** [comment]
thanks for your reply. What I dont get is the CursorRecyclerViewAdapter.java Is there no need to change code of this abstract class and just extend it?

**Comment by nesquena** [comment]
You should just be able to extend it as is.

**Comment by aoiserizawa** [comment]
wow thanks for that fast reply man. ill let you know if I had an error.

**Comment by aoiserizawa** [comment]
this is what I did on my onBindViewHolder

       @Override
       public void onBindViewHolder(ItemViewHolder viewHolder, Cursor cursor) {

        while (cursor.moveToNext()){
            int _id=cursor.getInt(cursor.getColumnIndex(MyDBHandler.COLUMN_ID));
            String title = cursor.getString(cursor.getColumnIndex(MyDBHandler.COLUMN_TITLE_REMINDER));
            String desc  = cursor.getString(cursor.getColumnIndex(MyDBHandler.COLUMN_DESC_REMINDER));
            String date  = cursor.getString(cursor.getColumnIndex(MyDBHandler.COLUMN_DATE_REMINDER));

            viewHolder.title.setText(title);
        }

am I doing it right??

**Comment by aoiserizawa** [comment]
Currently I have this code. 

RemindersAdapter.java

     public class RemindersAdapter extends     CursorRecyclerViewAdapter<RemindersAdapter.ItemViewHolder> {
       private final LayoutInflater inflater;
       List<ListInfo> data = Collections.emptyList();
       private Context context;
       ListInfo temporaryBucket;
    public RemindersAdapter(Context context, Cursor cursor){
        super(context, cursor);
        inflater = LayoutInflater.from(context);
        this.context = context;
    }

    @Override
    public ItemViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View view = inflater.inflate(R.layout.reminder_item, parent, false);

        ItemViewHolder holder = new ItemViewHolder(view);
        temporaryBucket = new ListInfo();

        return holder;
    }

    @Override
    public void onBindViewHolder(ItemViewHolder viewHolder, Cursor cursor) {
            int     id      = cursor.getInt(cursor.getColumnIndex(MyDBHandler.COLUMN_ID));
            String  title   = cursor.getString(cursor.getColumnIndex(MyDBHandler.COLUMN_TITLE_REMINDER));
            String  desc    = cursor.getString(cursor.getColumnIndex(MyDBHandler.COLUMN_DESC_REMINDER));
            String  date    = cursor.getString(cursor.getColumnIndex(MyDBHandler.COLUMN_DATE_REMINDER));

            viewHolder.title.setText(title);

    }

    class ItemViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener {
        TextView title;

        public ItemViewHolder(View itemView) {
            super(itemView);
            title = (TextView) itemView.findViewById(R.id.reminderTitle);

            itemView.setOnClickListener(this);

        }

        @Override
        public void onClick(View v) {
            int position = getLayoutPosition();

            Toast.makeText(context, "Clicked", Toast.LENGTH_SHORT).show();
        }
      }
    }

MyDBHandler.java


     public class MyDBHandler extends SQLiteOpenHelper{
      private static final int DATABASE_VERSION = 7;
      private static final String DATABASE_NAME = "paroah.db";
      public static final String TABLE_REMINDER = "reminders";
      public static final  String COLUMN_ID = "_id";
      public static final  String COLUMN_TITLE_REMINDER = "title";
      public static final  String COLUMN_DESC_REMINDER = "desc";
      public static final  String COLUMN_DATE_REMINDER = "date_created";
      private Cursor allReminders;
    public MyDBHandler(Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }


    @Override
    public void onCreate(SQLiteDatabase db) {
        String query = " CREATE TABLE "
                +TABLE_REMINDER+ "(" +
                COLUMN_ID +" INTEGER PRIMARY KEY AUTOINCREMENT,"+
                COLUMN_TITLE_REMINDER + " TEXT ,"+
                COLUMN_DESC_REMINDER + " TEXT ,"+
                COLUMN_DATE_REMINDER + " TEXT "+
                ");";

        db.execSQL(query);
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        Log.d("aoi", "Upgrading database from version " + oldVersion + " to "
                + newVersion + ", which will destroy all old data");
        try {
            db.execSQL("DROP TABLE IF EXISTS "+TABLE_REMINDER);
            onCreate(db);

        } catch (SQLException e) {
            Log.d("aoi",  "getting exception "
                    + e.getLocalizedMessage().toString());
        }
    }

    public void addReminder(ListInfo reminder ){
        ContentValues values = new ContentValues();
        values.put(COLUMN_TITLE_REMINDER, reminder.getTitle());
        values.put(COLUMN_DESC_REMINDER, reminder.getDesc());
        values.put(COLUMN_DATE_REMINDER, reminder.getDate());

        SQLiteDatabase db = getWritableDatabase();

        db.insert(TABLE_REMINDER, null, values);
        db.close();
    }

    public Cursor getAllReminders() {

        SQLiteDatabase db = getWritableDatabase();

        String query = "SELECT * FROM "+TABLE_REMINDER;

        allReminders = db.rawQuery(query, null);

        return allReminders;
    }

    }

what Im trying to do is when I click the Item in recyclerview it will display the information of the desc and date in the toast. How do I do that? TIA

**Comment by moizest89** [comment]
Hi man!!

I have my Adapter and within declare OnItemClickListener mItemClickListener and create a simple interaction like this:

```Java
public class ShowListAdapter extends RecyclerView.Adapter<ShowListAdapter.Holder>{
OnItemClickListener mItemClickListener;
.
.
.
public class Holder extends RecyclerView.ViewHolder implements View.OnClickListener{

     public Holder(View itemView) {
      super(itemView);
       itemView.setOnClickListener(this);
      }
       @Override
        public void onClick(View v) {
            if (mItemClickListener != null) {
                mItemClickListener.onItemClick(itemView, getAdapterPosition());
            }
        }
}

public interface OnItemClickListener {
        void onItemClick(View view, int position);
}
public void setOnItemClickListener(final OnItemClickListener mItemClickListener) {
        this.mItemClickListener = mItemClickListener;
}

}
```

and my activity only set setOnItemClickListener like this:

```Java
ShowListAdapter.OnItemClickListener onItemClickListener = new ShowListAdapter.OnItemClickListener(){

            @Override
            public void onItemClick(View view, int position) {
               //Do something
            }
        };

        this.mAdapter.setOnItemClickListener(onItemClickListener);
```

I hope will be of great help :)

**Comment by aoiserizawa** [comment]
thanks @moizest89  but what Im trying to figure out is on how to get the data from the database upon clicking the item from the recyclerview. As you can see on my onBindViewHolder Im getting Title,Desc and Date from the cursor but Im only setting the title in the recycler view, But what I want to happen is when I click the title it will also get the Desc and Date which will be shown in a toast for example.
