### ISSUE TITLE
Projecting Android Device to Computer

### ISSUE THREAD

**Issue by nesquena** [codepath/android_guides#108]
Guide on projecting Android Device to Computer. Following options exist:

 * [Mobizen](https://www.mobizen.com/?locale=en) - Web-based
 * [Using ChromeCast](https://support.google.com/chromecast/answer/6059461?hl=en) - Requires chromecase
 * [Mirroring360](http://www.mirroring360.com/how-it-works#steps) - Desktop App
 * [Droid@Screen](http://droid-at-screen.org/installation.html) - JAR Java App
 * [Vysor](http://www.vysor.io/) - Chrome Extension

**Comment by rkgra** [comment]
Thanks Nathan for details.

**Comment by nesquena** [comment]
http://guides.codepath.com/android/Presenting-an-Android-Device
