### ISSUE TITLE
saving-and-restoring-activity-state should mention onCreate

### ISSUE THREAD

**Issue by gregd** [codepath/android_guides#111]
On page
https://guides.codepath.com/android/Handling-Configuration-Changes#saving-and-restoring-activity-state
the onCreate method is not mentioned. Activity state can be also restored there. This is described quite well on http://stackoverflow.com/a/14676555/3315

Most important part from SO:
> Most implementations will simply use onCreate(Bundle) to restore their state, but it is sometimes convenient to do it here after all of the initialization has been done or to allow subclasses to decide whether to use your default implementation.

**Comment by nesquena** [comment]
I added a note [saying as much here](https://github.com/codepath/android_guides/wiki/Handling-Configuration-Changes/_compare/cc048ce119dd2b9d74176d2357ef55b4beaae9e7...75a165eced56422506a217a889baf82c0a7781ef). Thanks.
