### ISSUE TITLE
make RecyclerView content fit to screen

### ISSUE THREAD

**Issue by thelegend94** [codepath/android_guides#122]
Thank you so much for your article about "Using the RecyclerView" it's help me to understand how to use ```RecyclerView```, but I have simple question.
I try to use ```RecyclerView``` to make like this hashtags list:

![12355186_1061631603887809_474383095_n](https://cloud.githubusercontent.com/assets/16057272/11702114/03b4d5a2-9ee5-11e5-90bd-5edb3422e511.jpg)
I use ```TextView``` and set ```LinearLayoutManager``` to:
 ```
layoutManager.setOrientation(LinearLayoutManager.HORIZONTAL);
```

but content appear in one line and must use scroll to show other values!!
Is there way to make values shown as same as screenshot above?
Sorry to put my question here.

**Comment by ainesophaur** [comment]
Try using a grid layout instead of a linear layout.

Else post the XML for your container lay

**Comment by ainesophaur** [comment]
XML for the container layout and its parent

**Comment by nesquena** [comment]
Ditch the recyclerview for that case and use this https://github.com/ApmeM/android-flowlayout. Flowlayout was born for this use case.
