### ISSUE TITLE
Calling API using retrofit with dot net server

### ISSUE THREAD

**Issue by dhrumit123** [codepath/android_guides#126]
I am calling API using retrofit library with dot.net server. When I call API for first time it works fine but after some time or we can say after 3-4 minute it takes too much time to give response.
For more detail please see screen shot. I have called API with 3 minute time gap and printed API call time , API response time as well as time difference between API calling and API responding for retrofit, with default HTTP method and with volley library.
please suggest some solution for retrofit. Please not that I have used retrofit 1.9 library.
![api_test](https://cloud.githubusercontent.com/assets/7789149/12073416/015e67a0-b146-11e5-984b-d1c559df091b.png)

**Comment by danielgomezrico** [comment]
@dhrumit123 have you tested with https://github.com/square/retrofit/releases/tag/parent-2.0.0-beta3 ?
Also this should not be in retrofit repo?
Can you provide a code example?

**Comment by nesquena** [comment]
Probably belongs on the retrofit repo
