### ISSUE TITLE
Adding Guide for Using BaseAdapter with ListView

### ISSUE THREAD

**Issue by chi6rag** [codepath/android_guides#127]
Under the AdapterViews section, we have a section for making lists using ArrayAdapters but having one for BaseAdapters will be helpful too

**Comment by piotrek1543** [comment]
[+1]

**Comment by mayojava** [comment]
https://github.com/codepath/android_guides/issues/180

**Comment by nesquena** [comment]
See the [published version here](https://github.com/codepath/android_guides/wiki/Using-a-BaseAdapter-with-ListView)
