### ISSUE TITLE
how does an android app communicate to a pc via usb?

### ISSUE THREAD

**Issue by deostroll** [codepath/android_guides#130]
I am interested in learning about how an android app talks to a server hosted on a pc via the usb cable...

**Comment by Arn-O** [comment]
See my project:

https://github.com/Arn-O/py-android-accessory

;)

**Comment by iballan** [comment]
@deostroll  You have to use ADB to communicate with android device from pc

google adb, try to download it,
after connecting your device to pc, turn on USB debug mode from android device
then from the command line try this:
// to check connected devices
adb devices 
// to get the android shell 
adb shell

**Comment by nesquena** [comment]
http://guides.codepath.com/android/Sending-and-Receiving-Data-with-Sockets

**Comment by Vagekt** [comment]
Hi, 
I want to learn how a button in java which when pressed will act as pressing the power button of the Phone.
So basically when the button is pressed in PC, the phone will lock/unlock.
Need suggestions ...
