### ISSUE TITLE
Should I Use Fragments or Activities When Clicking On the Nav Drawer?

### ISSUE THREAD

**Issue by troy21688** [codepath/android_guides#131]
I am new to Android programming and came across this library as an amazing, efficient, and easy solution for my development. However, I was curious as to whether I should use fragments or activities for this NavDrawer. Basically, I am thinking I would host one MainActivity, and then each fragment would be placed inside that MainActivity on the NavDrawer click. 

Any advice is appreciated.

**Comment by jtcreative** [comment]
It depends on what you're switching and what that switch represents. If you are trying to keep the same design context and you just want to switch screens, then using Fragments would be great  to use. If you are performing a completely new set of different operations and goals, then a new activity might be better.
