### ISSUE TITLE
qr code library list

### ISSUE THREAD

**Issue by maxim-pandra** [codepath/android_guides#132]
Hi everyone,

There's nice qr-code library wich is not included in the list. 
https://github.com/journeyapps/zxing-android-embedded

I think it's good enough to be included)

**Comment by nesquena** [comment]
[Added](https://github.com/codepath/android_guides/wiki/Must-Have-Libraries#scanning), thanks

**Comment by kylejablonski** [comment]
Hey, I have also created a simple library project for creating all codes
(using ZXing Core) called BarcodeAgent
<https://github.com/kylejablonski/BarcodeAgent>
