### ISSUE TITLE
Vet Parse open source

### ISSUE THREAD

**Issue by rogerhu** [codepath/android_guides#138]
Action items:

- [x] Validate Heroku/AWS install instructions (https://github.com/codepath/android_guides/wiki/Configuring-a-Parse-Server)
- [x] Enable push notification support (https://github.com/codepath/android_guides/wiki/Configuring-a-Parse-Server#enabling-push-notifications)
- [x] Validate local setup
- [x] Figure out if there are any blocking bugs in your group projects (query issues, load, etc.): https://github.com/ParsePlatform/parse-server/issues
- [x] Submit any bug issues 
- [ ] Submit patches
- [x] Help document workarounds in guides

### Heroku/AWS installation

1. Get a Parse server working on AWS or Heroku http://guides.codepath.com/android/Configuring-a-Parse-Server

### Local testing 

Follow instructions based on https://github.com/ParsePlatform/parse-server-example#for-local-development

1. Install NodeJS locally
      a. Get the node.js installer - https://nodejs.org/en/
      b. Install MongoDB - http://docs.mongodb.org/master/tutorial/install-mongodb-on-os-x/

2. Fork and download Parse server code.
      ```bash 
      git clone https://github.com/ParsePlatform/parse-server
      git clone https://github.com/ParsePlatform/parse-server-example
     ```

3. Get server running locally
      ```bash
      cd parse-server-example
      npm install
      npm start
      ```

4. Figure out the IP address of your machine (i.e. `ifconfig en0`).

5. Point your clients at an IP address:

    Android:

    ```java
        Parse.initialize(new Parse.Configuration.Builder(this)
                .applicationId("myAppId")
                .server("http://192.168.3.116:1337/parse/")
   ```

#### Making changes

If you wish to make changes to the Parse source code, you can make changes to `node_modules/parse-server`. 

You can also make changes to the parse-server code and install the package by dong the following:

1. Edit dependencies in package.json to reference the parse server locally:

     ````javascript
     "dependencies": {

       "parse-server": "file:../parse-server"
     },
     ```

2. Make any changes.

3. To force reinstall, `npm install parse-server`

**Comment by nesquena** [comment]
@rogerhu should we close this?
