### ISSUE TITLE
Add Bottom Sheets and Vector Drawable Guides

### ISSUE THREAD

**Issue by nesquena** [codepath/android_guides#140]
- [x] Bottom sheets
- [x] Vector drawables

References:

 * http://android-developers.blogspot.com/2016/02/android-support-library-232.html
 * http://stackoverflow.com/a/35620244
 * http://developer.android.com/training/material/drawables.html#VectorDrawables
 * http://developer.android.com/training/material/animations.html#AnimVector
 * http://developer.android.com/reference/android/graphics/drawable/VectorDrawable.html

**Comment by nesquena** [comment]
cc @rogerhu

**Comment by rogerhu** [comment]
Blocking bug:

https://code.google.com/p/android/issues/detail?id=201817 -> 

```
Devices/Android versions reproduced on: Samsung Galaxy Tab 2 (GT P5210) / KitKat 4.4.2

Add a spinner to any activity anywhere in the layout xml file:

<Spinner
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    />

App crashes with exception:
android.content.res.Resources$NotFoundException: File res/drawable/abc_spinner_textfield_background_material.xml from drawable resource ID #0x7f020040

```

**Comment by nesquena** [comment]
Re vector drawables, early stab here: https://github.com/codepath/android_guides/wiki/Drawables#vector-drawables

**Comment by aphexcx** [comment]
I'm implemented Bottom Sheets myself for a project, I can post some trip reports from my journey here :) So far I'm trying things from here: http://stackoverflow.com/questions/35618998/how-to-implement-bottom-sheets-using-new-design-support-library-23-2

**Comment by Ralphilius** [comment]
I have also implemented BottomSheetFragment for my project by following this tutorial: http://code.tutsplus.com/articles/how-to-use-bottom-sheets-with-the-design-support-library--cms-26031

**Comment by nesquena** [comment]
You can see our guide on [bottom sheets here](http://guides.codepath.com/android/Handling-Scrolls-with-CoordinatorLayout#bottom-sheets). I added a link to that tutorial referenced above. [Vector drawables guide](https://github.com/codepath/android_guides/wiki/Drawables#vector-drawables) is done now as well. Closing.
