### ISSUE TITLE
how to change tablayout background color?

### ISSUE THREAD

**Issue by kevinisbest** [codepath/android_guides#144]
hi!! thanks your repo
like title
i try`app:tabBackground` and`android:background`
but the background doesn't change
how do i solve it

use`app:tabBackground`
![image](https://cloud.githubusercontent.com/assets/10130649/13548486/85eb6960-e32c-11e5-8b73-68dc5c9985d8.png)
use`android:background`
![image](https://cloud.githubusercontent.com/assets/10130649/13548488/91c8022a-e32c-11e5-977b-91c2c3b011e0.png)

the same :(

**Comment by Marchuck** [comment]
Have you tried set these attributes by code? Could you show some code?

**Comment by kevinisbest** [comment]
because i have two styles to switch
so i define the name in attrs.xml
![image](https://cloud.githubusercontent.com/assets/10130649/13553094/3e84ebb0-e3b7-11e5-8d7f-842473bff56f.png)
and this is my styles
![image](https://cloud.githubusercontent.com/assets/10130649/13553096/694cb580-e3b7-11e5-8881-a7137105ae85.png)
in my layout
![image](https://cloud.githubusercontent.com/assets/10130649/13553098/958aaada-e3b7-11e5-8895-9340e7bc48b5.png)

if there is something wrong please tell me, i am the newbie in android

**Comment by Marchuck** [comment]
try change "android:colorPrimary" to "colorPrimary" (and delete all prefixes "android:" in both styles).
Who is parent of "AppTheme" ?

**Comment by kevinisbest** [comment]
after deleting all prefixes "android:" 
![image](https://cloud.githubusercontent.com/assets/10130649/13558899/79dc95f6-e447-11e5-94be-e66cf5b21c11.png)

ther are some errors
![image](https://cloud.githubusercontent.com/assets/10130649/13559063/dc2578f2-e449-11e5-9da5-6583227788aa.png)

and the parent of AppTheme is
![image](https://cloud.githubusercontent.com/assets/10130649/13558880/13585b80-e447-11e5-957e-9128c885bc92.png)

**Comment by iBobb** [comment]
I'm not sure what's causing your issue but you might find this information interesting. The newest update to the support library (_23.2.0_) has a **Day/Night Theme**.
http://android-developers.blogspot.co.uk/2016/02/android-support-library-232.html

>  this theme allows apps to easily support both a Light and Dark theme, effectively switching from a Light theme to a Dark theme based on whether it is ‘night’.

**Comment by kevinisbest** [comment]
ok i will try this
thank you anyway

**Comment by iBobb** [comment]
Do you have the support libraries downloaded? I just used
` <item name="android:textColorPrimary">@color/myColor</item>`
and it worked without a problem. The thing is I have `<resources xmlns:tools="http://schemas.android.com/tools">` declared right at the top of the file before anything else.
