### ISSUE TITLE
removeDialog() vs dismissDialog() vs dismiss()

### ISSUE THREAD

**Issue by Yousha** [codepath/android_guides#149]
Different between `removeDialog()` and `dismissDialog()` and `dismiss()`:

`removeDialog(int id)`: It also dismisses the dialog with the specified id. Means it hides that particular dialog and in addition cleans up all the references by the Activity and hence cannot be restored in future. **Deprecated in API 13.**

`dismissDialog(int id)`: Dismisses the dialog with the specified id. It only hides the dialog but still keeps the internal references by the Activity which contains this dialog so that it can be restored in future. **Deprecated in API 13.**

`dismiss()`: This method operates on a particular dialog because it is a method of Dialog class. It also dismisses the dialog. You have to own a valid dialog in order to dismiss it else you'll get exception. (Recommended)

[Source](http://stackoverflow.com/a/36120864/1429432)

**Comment by nesquena** [comment]
Both of the other 2 are deprecated in API 13. `dismiss` is the only one that should be used. I have [added as much here](https://github.com/codepath/android_guides/wiki/Using-DialogFragment/_compare/d83d74b04e0fc37f3bcfc96f740b0ea461e4e827...8adf5f883c23199dd18ecdd192ec3826c960949c) with link to that source.
