### ISSUE TITLE
This is not working on old version androids

### ISSUE THREAD

**Issue by WilliamGjerde** [codepath/android_guides#150]
SwipeRefreshLayout is working on Android Version 5.0.
But it's not working on 4.0 and 4.3.
How can I solve this problem?
Please help me.

**Comment by nesquena** [comment]
SwipeRefreshLayout using the support version [as outlined here](http://guides.codepath.com/android/Implementing-Pull-to-Refresh-Guide) works in nearly all versions of Android.
