### ISSUE TITLE
Sharing-Content-with-Intents.md

### ISSUE THREAD

**Issue by chug2k** [codepath/android_guides#152]
Sorry, not sure how to submit a PR, but here's a link to an online diff.

Correct me if I'm wrong, but the code as written would crash if the user clicks 'share' before the image finishes downloading. It might be best to defer attaching anything until the image finishes downloading. Alternatively, you could disable/enable the share button. Also, I don't think `shareIntent` needs to be an instance variable.

http://www.mergely.com/ychxP6Ov/

**Comment by nesquena** [comment]
Yep, fixed.
