### ISSUE TITLE
App Deep Linking/App Links

### ISSUE THREAD

**Issue by aimanbaharum** [codepath/android_guides#156]
Hey guys,

I haven't found any guides on app **deep linking/app linking/app indexing** implementation here. Could someone explain on how to use it in an app?

I understand the concept of having to click a hyperlink and automatically direct user to an Activity of our app, but that's it. I know there's a lot more to it, like linking it to analytics and such. But it gets overwhelmed at some point.

However, I have some confusion regarding the use of [AppIndex](https://developers.google.com/app-indexing/android/publish#add-google-play-services) API; like what's the difference between having those in my code rather than just use `Intent.getData()` stuff.

Mainly, I do not get the flow of this whole App Linking/Deep Linking stuff. I hope someone could clear it a bit in android_guides for the community to learn. Thanks! :-)

**Comment by nesquena** [comment]
Also to include:

 * Usage of `autoVerify`: <https://developer.android.com/training/app-links/index.html>

**Comment by aimanbaharum** [comment]
Although not very technical and Android-focused, but I'd like to share how Telegram Messenger did its App/Deep Linking mechanism.

Please note, this is not the guide on how to really implement App Link/Deep Link in an Android app, rather the typical (rough) flow and behavior on different scenario of user states. I also don't think this is the only way to do it, there might be many. Appreciate it if someone could share.

**Scenario 1: App not installed**

```
a) Clicks external link (eg. https://telegram.me/joinchat/{id})  
b) Opens a webpage (telegram website)  
    i. link to playstore/appstore  
    ii. link to join group - unclickable because URL is a deeplink (eg. tg:join?invite={id})
```

**Scenario 2: Installed but not logged in**

```
a) Clicks external link
b) Opens a webpage (telegram website) [similar to 1b]
c) Automatically redirects user to app (using window.location)
d) App checks if user logged in - prompts user to log in
    - Success log in
        - show MainActivity of app
        - user need to go back to website to click Join Group link (1bi)
    - Cancel log in
        - show MainActivity of app
        - back to website (2b)
```

**Scenario 3: Installed and logged in**

```
a) Clicks external link
b) Redirects to app
c) Directly prompt user to join group
    - Yes - register user
    - No - Do nothing
```

**Comment by rogerhu** [comment]
Added section of the guide here:

http://guides.codepath.com/android/Using-Intents-to-Create-Flows#receiving-implicit-intents

There is an AirBnb library that makes it easy to annotate your activities with URL patterns to launch certain activities.

The app indexing library seems to be used for indexing search results in the Google play store and potentially launching your app.  I think it's supplementary to deep liking.  I have no direct experience though.

**Comment by nesquena** [comment]
👍  This is great @rogerhu, thanks.

**Comment by rogerhu** [comment]
Added autoverify stuff now.
