### ISSUE TITLE
RecyclerViewSimpleTextViewHolder not found

### ISSUE THREAD

**Issue by AdrianPock** [codepath/android_guides#162]
As 'android.R.layout.simple_list_item_1' is built in does this apply to 'RecyclerViewSimpleTextViewHolder' (as used in [Heterogenous Layouts inside RecyclerView](https://github.com/codepath/android_guides/wiki/Heterogenous-Layouts-inside-RecyclerView)) or do I have to make it myself?

If built in where is it?

**Comment by nesquena** [comment]
`RecyclerViewSimpleTextViewHolder` is a fallback holder class if the other view holders aren't found, and isn't really necessary. It is not built in, so if you want to include it, you'd have to create that yourself. You can also omit no item in the "default" case.
