### ISSUE TITLE
Change "Subscriber" to "Observer" in RxJava.md

### ISSUE THREAD

**Issue by arriolac** [codepath/android_guides#166]
Although `Subscriber` is interchangeably used with `Observer` in Rx. The top-level interface is actually `Observer` and `Subscriber` is only one implementation of `Observer`.

https://hackmd.io/KYNg7ArAnAHDBmBaAjPYVEBYwCMSKmSiWQBMBjABmQCZ4BmKc4UoA===

**Comment by rogerhu** [comment]
Thanks.  Copied the changes (https://github.com/codepath/android_guides/wiki/RxJava/0132a16cbfacc0fd36b01a1530dc858739684439).  Anything else?

**Comment by arriolac** [comment]
@rogerhu Will look through it again—that's all I have for now. :)

**Comment by rogerhu** [comment]
Thanks for all the feedback.  Please feel free  to revise directly if you find other issues.
