### ISSUE TITLE
Information in RxJava about Hot vs Cold Observable is incorrect

### ISSUE THREAD

**Issue by arriolac** [codepath/android_guides#167]
**Cold Observable** means that the sequence is preserved on each new subscription. This means that retrofit by default operates as a *cold* Observable (documentation says *hot*) since every call to a Retrofit function that emits an Observable will evoke a network request.

**Hot Observable** means that the sequence is not preserved on each new subscription. For example, say the Observable emitted the values 1, 2, and 3 and a new Observer subscribes to that Observable, that Observer would not get the emissions 1, 2, and 3 since the Observable is already **hot**, it will only get subsequent emissions.

Wanted to bring this up here before sending a diff.

**Comment by nesquena** [comment]
Thanks for reviewing the guide and catching that. Would be great if you can [update the guide directly](https://github.com/codepath/android_guides/wiki/RxJava/_edit) on the wiki as our resident RxJava expert. Feel free to make other changes to it as well, the guide is still definitely in it's early stages.

**Comment by rogerhu** [comment]
I've reversed the terms.
