### ISSUE TITLE
Guide on Retrolambda

### ISSUE THREAD

**Issue by nesquena** [codepath/android_guides#168]
We should have a wiki guide on retrolambda library directly on the guides. Here is a good starting point for the guide: https://medium.com/android-news/retrolambda-on-android-191cc8151f85#.ykewuqug5

**Comment by rogerhu** [comment]
Is it really needed now?

http://www.androidheadlines.com/2016/03/androids-jack-compiler-says-hello-to-java-8-in-android-n.html

**Comment by nesquena** [comment]
Yeah that's a fair point, this becomes irrelevant soon. From the article:

> The exciting thing here is that Lambda Expressions will work on versions of Android back to versions 2.3, Gingerbread which launched with the Nexus S. This makes it worth it for a developer to get familiar with the new Java 8 support in Android as it will be leveraged by lots of different users out there, not just those running Android N.

**Comment by nesquena** [comment]
I think this is done: https://github.com/codepath/android_guides/wiki/Lambda-Expressions. Thanks @rogerhu!
