### ISSUE TITLE
Starting Service / GCM tutorial

### ISSUE THREAD

**Issue by EmreSURK** [codepath/android_guides#171]
I can not able to see where we starting RegistirationIntentService.
Please add this line to second major topic if not exist;
startService(new Intent(MainActivity.this, RegistrationIntentService.class));

If exist, forgive me.
Thanks.

**Comment by nesquena** [comment]
Isn't there http://guides.codepath.com/android/Google-Cloud-Messaging#create-a-instanceid-listenerservice?

**Comment by EmreSURK** [comment]
Where do we starting MyInstanceIDListenerService ?
I was only able to get pushToken after i started RegistirationIntentService from my MainActivity.
Without the line I offered nothings happen.
It seems we does not start both of these services anywhere.

**Comment by rogerhu** [comment]
MyInstanceIDListenerService starts up as a background service and will launch the intent service onTokenRefresh() as mentioned in the guide: http://guides.codepath.com/android/Google-Cloud-Messaging#create-a-instanceid-listenerservice

Yeah we should mention you need to start the intent service in OnCreate() as shown in this example:

https://github.com/googlesamples/google-services/blob/master/android/gcm/app/src/main/java/gcm/play/android/samples/com/gcmquickstart/MainActivity.java#L71-L75

**Comment by rogerhu** [comment]
Updated here: https://github.com/codepath/android_guides/wiki/Google-Cloud-Messaging#implement-a-registration-intent-service

You only need to initiate the RegistrationIntentService though, not the InstanceIDListenerService.

**Comment by nesquena** [comment]
This is great, thanks for closing the loop on that
