### ISSUE TITLE
what is your Goal?

### ISSUE THREAD

**Issue by axd1967** [codepath/android_guides#174]
7276428357f11b9275c39cf90157a75c64ebbe97 introduces the "The CodePath Goal" link target but after that commit, that link will never be implemented.

(https://github.com/codepath/android_guides/wiki/The-CodePath-Goal)

**Comment by nesquena** [comment]
Was moved here: https://github.com/codepath/android_guides/wiki/CodePath-Goal.

**Comment by axd1967** [comment]
still not OK in https://github.com/codepath/android_guides

this wiki/sourcecode mix is confusing. (#82?)
