### ISSUE TITLE
Adding Guide for Using BaseAdapter with ListView - Enhancement

### ISSUE THREAD

**Issue by mayojava** [codepath/android_guides#180]
A guide on using ListView with BaseAdapter
https://hackmd.io/s/HJ7FmxlE

**Comment by nesquena** [comment]
This is great, thank you for contributing! I've made a few tweaks and [deployed it here](https://github.com/codepath/android_guides/wiki/Using-a-BaseAdapter-with-ListView) with a link from the homepage [here](https://github.com/codepath/android_guides/wiki#adapterviews)! I've added a section at the bottom to attribute you as the original author.

**Comment by mayojava** [comment]
Great. Thanks.
