### ISSUE TITLE
Endless Scrolling with RecyclerView question

### ISSUE THREAD

**Issue by PingForward** [codepath/android_guides#181]
In this example [Endless Scrolling with RecyclerView](https://github.com/codepath/android_guides/wiki/Endless-Scrolling-with-AdapterViews) we pass `LinearLayoutManager` to constructor of `EndlessRecyclerViewScrollListener` class is this the best approach?
With this implementation we can't use `GeidLayoutManager` for example and we create a new instance of `LinearLayoutManager` inside `ScrollListener` class. Why not use abstract methods to get total and first visible items?

**Comment by PingForward** [comment]
Also there is an instance of RecyclerView which we can use to get layout manager.
`public void onScrolled(RecyclerView recyclerView, int dx, int dy)`

**Comment by rogerhu** [comment]
Take a look at http://guides.codepath.com/android/Endless-Scrolling-with-AdapterViews-and-RecyclerView.   Somehow this page was brought back alive and doesn't contain the newer layout maangers.
