### ISSUE TITLE
open-source-apps page has incorrect link for Rest Client sample app

### ISSUE THREAD

**Issue by sonnytron** [codepath/android_guides#187]
Given I am viewing open source apps on the [sample projects page from Cliffnotes, here](http://guides.codepath.com/android/Sample-Android-Apps#codepath-code-samples)  
And I have clicked on "Android Rest Client Multi-Service Demo"
The link sends me to [this repository](https://github.com/codepath/multi_fragments_demo)  
Is the correct repo [this](https://github.com/codepath/android-multiservice-oauth-demo) one?

**Comment by nesquena** [comment]
Yep, fixed, thanks!
