### ISSUE TITLE
How to call showRational() method for @OnNeverAskAgain event

### ISSUE THREAD

**Issue by roostaamir** [codepath/android_guides#188]
I am using Permission dispatcher plugin and when the user clicks neve ask again, the activity hangs.
I want to show the user the `Rational` dialog when the user checks the `never ask again dialog` and enters the application again.

currently the app will freeze when the user checks never show this again

what should I do?

**Comment by pranaypatel512** [comment]
To know if the user denied with "never ask again" you can check again the `shouldShowRequestPermissionRationale` method in your `onRequestPermissionsResult` when the user did not grant the permission.

```
@Override
public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
    if (requestCode == REQUEST_PERMISSION) {
        // for each permission check if the user grantet/denied them
        // you may want to group the rationale in a single dialog,
        // this is just an example
        for (int i = 0, len = permissions.length; i < len; i++) {
            String permission = permissions[i];
            if (grantResults[i] == PackageManager.PERMISSION_DENIED) {
                boolean showRationale = shouldShowRequestPermissionRationale( permission );
                if (! showRationale) {
                    // user denied flagging NEVER ASK AGAIN
                    // you can either enable some fall back,
                    // disable features of your app
                    // or open another dialog explaining
                    // again the permission and directing to
                    // the app setting
                } else if (Manifest.permission.WRITE_CONTACTS.equals(permission)) {
                    showRationale(permission, R.string.permission_denied_contacts);
                    // user denied WITHOUT never ask again
                    // this is a good place to explain the user
                    // why you need the permission and ask if he want
                    // to accept it (the rationale)
                } else if ( /* possibly check more permissions...*/ ) {
                }
            }
        }
    }
}
```

Check more [Android M - check runtime permission - how to determine if the user checked “Never ask again”?](http://stackoverflow.com/questions/30719047/android-m-check-runtime-permission-how-to-determine-if-the-user-checked-nev)

**Comment by rogerhu** [comment]
Can you also just use @OnNeverAskAgain() decorator as described in http://guides.codepath.com/android/Managing-Runtime-Permissions-with-PermissionsDispatcher#permission-event-handling?

**Comment by rogerhu** [comment]
Updated https://github.com/codepath/android_guides/wiki/Understanding-App-Permissions#runtime-permissions as well to include this issue.
