### ISSUE TITLE
[REQUEST] Getting an Lat, Lon

### ISSUE THREAD

**Issue by MTRNord** [codepath/android_guides#193]
Would be nice to have a few lines about how to get the Location Lat and Long. There are mostly only fragments in the Internet. (or I search wrong)

**Comment by randomlock** [comment]
Android Developer website contain plenty of information about this - https://developer.android.com/training/location/retrieve-current.html

**Comment by nesquena** [comment]
Also https://guides.codepath.com/android/Retrieving-Location-with-LocationServices-API
