### ISSUE TITLE
use SmartFragmentStatePagerAdapter which is deployed for caching fragmets

### ISSUE THREAD

**Issue by tux-world** [codepath/android_guides#194]
Hi, how can i use ```getRegisteredFragment``` method on ```SmartFragmentStatePagerAdapter``` deployed viewPager? is it for check caching fragment?

**Comment by tvishal** [comment]
This is an automatically generated message.

tvishal@yahoo-inc.com is no longer with Yahoo! Inc.

Your message will not be forwarded.

If you have a sales inquiry, please email yahoosales@yahoo-inc.com and someone will follow up with you shortly.

If you require assistance with a legal matter, please send a message to legal-notices@yahoo-inc.com

Thank you!

**Comment by nesquena** [comment]
Yes you use it to get out different fragments loaded into the ViewPager and it caches then.

**Comment by tux-world** [comment]
@nesquena it meand befor attach fragment to such a ViewPager i must check attached fragment with  ```getRegisteredFragment``` if returned fragment is equal with new activity then no necessary to attach again, is it correct?

**Comment by tux-world** [comment]
Is that correct?

Why closed unanswerd issue?

**Comment by nesquena** [comment]
Sorry, I didn't understand the question. The viewpager generates the fragment children pages for you in the adapter, you use `getRegisteredFragment` to retrieve them out.

**Comment by tux-world** [comment]
No problem. Could you help me how can i cach it and retrieve cached
fragment? Is it work for phone roration?

**Comment by nesquena** [comment]
The adapter manages all that for you, no need to do extra caching: http://stackoverflow.com/a/7098081

**Comment by tux-world** [comment]
Thanks
