### ISSUE TITLE
Added `Robotium in Google's Espresso way`

### ISSUE THREAD

**Issue by piotrek1543** [codepath/android_guides#200]
Hi,

I've already added new paragraph to existing [**UI-Testing-with-Robotium**](https://github.com/codepath/android_guides/wiki/UI-Testing-with-Robotium)

**Motivation (shortly):**
-  `ActivityInstrumentationTestCase2 is deprecated`
-  adding support for new `Android Testing Support Library`
-  reducing `Robotium` tests generated boilerplate code 
-  no more `testSomethingToDo` classes name
-  using `@Test` and `@Rule` annotations

Waiting for your comments, suggestions and help to improve that.

Cheers

**Comment by rogerhu** [comment]
Updated fixes here: https://github.com/codepath/android_guides/wiki/UI-Testing-with-Robotium/_compare/09b2c1cc32dd8c07f133b0be3d0df8880cd06882...cba62d1055fbec045368581a1b3ca7dc215f6673

**Comment by rogerhu** [comment]
Anything else?

**Comment by piotrek1543** [comment]
Nope. Thanks for help.
