### ISSUE TITLE
Error in FilterColorDescriptor example?

### ISSUE THREAD

**Issue by RobLewis** [codepath/android_guides#202]
OK, admittedly I'm new to Android but I can't make any sense out of this: [https://github.com/codepath/android_guides/wiki/Replacing-Enums-with-Enumerated-Annotations](url)

In the FilterColorDescriptor example, you're defining _int_ constants and initializing them with _String_ values. What the hey?

**Comment by nesquena** [comment]
Fixed, thanks!
