### ISSUE TITLE
Setting up build variant no longer required to run tests in AS2.0

### ISSUE THREAD

**Issue by lidderupk** [codepath/android_guides#203]
The following is no longer required in [android studio setup for espresso](https://guides.codepath.com/android/UI-Testing-with-Espresso#android-studio-setup) as both junit and instrumentation tests are included by default since AS 2.0. I wanted to check with you before removing from the guide. @nesquena 

_**Next, open the Build Variants window and make sure the Test Artifact is set to Android Instrumentation Tests. Without this, our tests won't be included in the build.**_

**Comment by nesquena** [comment]
Yep I believe you are correct, please do adjust the guide accordingly. Thanks
