### ISSUE TITLE
Add Parse Dashboard to Guide

### ISSUE THREAD

**Issue by nesquena** [codepath/android_guides#204]
Add notes on setting up the Parse Dashboard to the [configuring Parse guide](http://guides.codepath.com/android/Configuring-a-Parse-Server)

 * https://www.codementor.io/nodejs/tutorial/deploy-parse-dashboard-on-heroku

**Comment by rogerhu** [comment]
Yeah the big thing is that you have to consider the app for basic authentication (https://github.com/ParsePlatform/parse-dashboard#configuring-basic-authentication).  

The guide already has docs about how to setup a Parse dashboard locally and have it talk directly to the hosted Parse instance (http://guides.codepath.com/android/Configuring-a-Parse-Server#parse-dashboard)

**Comment by nesquena** [comment]
Ah okay thanks for pointing that out. This may be redundant then. Feel free to close.
