### ISSUE TITLE
Transitions API framework

### ISSUE THREAD

**Issue by rogerhu** [codepath/android_guides#207]
- [x] Now backported down to Android 4.0 (API 14) with support design library 24.2.0
- [x] Add section on how to allow for view hierarchies to be animated and common use cases
- [x] Modify [activity and fragment transition guide](http://guides.codepath.com/android/Animations) to use the new transitions API (cannot be done, only for view transitions, see https://plus.google.com/110757386741030050881/posts/gzzp2MZ1Wgn)
- [x] Modify shared [element transitions doc](https://guides.codepath.com/android/Shared-Element-Activity-Transition)?  (Not sure why `android:windowContentTransitions` does not work -- possible Android Studio XML editor hasn't been updated?) (cannot be done, transitions API only works for view transitions)

References:

  - http://www.youtube.com/watch?v=S3H7nJ4QaD8
  - https://github.com/lgvalle/Material-Animations
  - https://www.reddit.com/r/androiddev/comments/4y70e7/android_support_library_v242_released/
  - http://lucasr.org/2014/03/13/how-android-transitions-work/
    - always add addTarget to transitions
  - Make sure to update view references when new scene (http://lucasr.org/2014/03/13/how-android-transitions-work/)

**Comment by tvishal** [comment]
This is an automatically generated message.

tvishal@yahoo-inc.com is no longer with Yahoo! Inc.

Your message will not be forwarded.

If you have a sales inquiry, please email yahoosales@yahoo-inc.com and someone will follow up with you shortly.

If you require assistance with a legal matter, please send a message to legal-notices@yahoo-inc.com

Thank you!

**Comment by nesquena** [comment]
Thanks for documenting this Roger. Additional related resources for the Transitions animation framework:

* https://medium.com/@andkulikov/animate-all-the-things-transitions-in-android-914af5477d50#.c93tot4td
* https://www.bignerdranch.com/blog/building-animations-android-transition-framework-part-1/
* https://www.bignerdranch.com/blog/building-animations-android-transition-framework-part-2/
* https://developer.android.com/training/transitions/index.html
* https://www.youtube.com/watch?v=S3H7nJ4QaD8
* https://possiblemobile.com/2013/11/new-transitions-framework/

**Comment by rogerhu** [comment]
Added those links and created a draft here: https://github.com/codepath/android_guides/wiki/View-Hierarchy-Animations

**Comment by nesquena** [comment]
👍 This is awesome, this gap in our animations guides is finally gone thanks to your work! Thanks so much.
