### ISSUE TITLE
RecyclerView and SnapHelper

### ISSUE THREAD

**Issue by rogerhu** [codepath/android_guides#208]
https://rubensousa.github.io/2016/08/recyclerviewsnap?utm_source=androiddevdigest

**Comment by nesquena** [comment]
I also added this section not to long ago on snap to center effect: http://guides.codepath.com/android/Using-the-RecyclerView#snap-to-center-effect but never found a suitable GIF to demonstrate the effect :(

**Comment by nesquena** [comment]
Added! https://github.com/codepath/android_guides/wiki/Using-the-RecyclerView#snap-to-center-effect
