### ISSUE TITLE
Image to all resolutions

### ISSUE THREAD

**Issue by sibelius** [codepath/android_guides#209]
How can I convert an image to al resolutions of drawables?

I don't want to create a launcher or action bar or notification icon, I just wanna a normal image

**Comment by nesquena** [comment]
See: https://github.com/codepath/android_guides/wiki/Working-with-the-ImageView#final-android-resizer

**Comment by alikyo** [comment]
What about SVG ? is now well supported :)

**Comment by sibelius** [comment]
tks for the answer
