### ISSUE TITLE
Building your own Android library

### ISSUE THREAD

**Issue by dholdaway** [codepath/android_guides#212]
When following the Building your own Android library tutorial, 

* What went wrong:
Execution failed for task ':androidlib:uploadArchives'.
> Could not publish configuration 'archives'
   > Failed to deploy artifacts/metadata: No connector available to access repository remote (s3://XXX/android/snapshots) of type default using the available factories WagonRepositoryConnectorFactory

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

any suggestions ?

**Comment by nesquena** [comment]
@rogerhu

**Comment by rogerhu** [comment]
Yeah the instructions only work if you are using mavenDeployer with a local file.  Here is the stock way of doing it if you are using an S3 URL -- I am going to update the guides to include POM stuff.

```
apply plugin: 'maven'

def isReleaseBuild() {
    return VERSION_NAME.contains("SNAPSHOT") == false
}

uploadArchives {
    repositories {
        maven {
            if (isReleaseBuild()) {
                url "s3://yours3bucket/folder"
            } else {
                url "s3://yours3bucket/folder"
            }
            credentials(AwsCredentials) {
                accessKey AWS_ACCESS_KEY
                secretKey AWS_SECRET_KEY
            }
        }
    }
}

```

**Comment by rogerhu** [comment]
See update: https://github.com/codepath/android_guides/wiki/Building-your-own-Android-library#setting-up-a-private-amazon-s3-maven-repository

Does this fix your issue?
