### ISSUE TITLE
Refresh Fragment inside ViewPager

### ISSUE THREAD

**Issue by nuhkoca** [codepath/android_guides#216]
Hi, I have Swipe Tab Layout and it has 21 tabs. I use only one Fragment for each Tab. I want to refresh the fragment where any tab is selected. How do I do that? Thanks.

**Comment by ibtehaz-shawon** [comment]
Based on Guesses:

1. Derive your Pager_adapter class as -- extends FragmentStatePagerAdapter (FragmentStatePagerAdapter destroys and creates them anew as they are shifted in and out of view.)
2. Make sure you are not calling setRetainInstance(true) in any of your  Fragments, else they won't be recreated.
3. Add viewPager.setOffscreenPageLimit(0);
4. create the structure as Activity -> Fragment -> ViewPager -> Nested Fragments

src: http://stackoverflow.com/a/29100155/5876080 

PS: Try posting in stackoverflow as well.

**Comment by nuhkoca** [comment]
Thank you @ibtehaz-shawon I'll try. If it don't work I am gonna write again :) Thanks.
