### ISSUE TITLE
SQLiteOpenHelper (Memory Leak)

### ISSUE THREAD

**Issue by rodgarcialima** [codepath/android_guides#221]
**Android hint:**

> Do not place Android context classes in static fields (static reference to DbHelper which has field context pointing to Context); this is a memory leak (and also breaks Instant Run)

How can I solve this possible problem?

Cheers

**Comment by rogerhu** [comment]
Use Activity context and don't use static fields

See: http://android-developers.blogspot.com/2009/01/avoiding-memory-leaks.html
