### ISSUE TITLE
App Shortcuts on Android 7.1

### ISSUE THREAD

**Issue by msomu** [codepath/android_guides#224]
I have drafted it [here](https://hackmd.io/BwFgRgDAJgxgjATgLQCYCmcpJGg7CpYNeJAVmKlJTnFIDMwg?both), please feel free to edit it and make it perfect.

**Comment by nesquena** [comment]
Looks like a solid starting point! Published here now: https://github.com/codepath/android_guides/wiki/Creating-App-Shortcuts-in-Launcher. Improvements welcome!
