### ISSUE TITLE
Mistake in the article Google Play Style Tabs using TabLayout

### ISSUE THREAD

**Issue by stepanov-standy** [codepath/android_guides#228]
Hi Team,

I find your guide really cool! Thanks. Looks like you have one small but quite time consuming mistake in the article [Google Play Style Tabs using TabLayout](https://guides.codepath.com/android/Google-Play-Style-Tabs-using-TabLayout#setup-sliding-tabs).

Instead of using Support Fragment Manager:

`ViewPager viewPager = (ViewPager) findViewById(R.id.viewpager);
        viewPager.setAdapter(new SampleFragmentPagerAdapter(getSupportFragmentManager(), 
            MainActivity.this));`

 we should use Child Fragment Manager:

`ViewPager viewPager = (ViewPager) findViewById(R.id.viewpager);
        viewPager.setAdapter(new SampleFragmentPagerAdapter(getChildFragmentManager(), 
            MainActivity.this));`

Otherwise the content will be wiped after you switch the fragments in the app and return back to TabLayout.

**Comment by mhussien86** [comment]
good catch :)

**Comment by nesquena** [comment]
`getChildFragmentManager` is only for when a ViewPager is itself within a Fragment. The example in the guide has the ViewPager inside the activity. Neither are wrong but it wouldn't make sense to use `getChildFragmentManager` inside of the Activity. Maybe best thing would be to add a note that inside of a Fragment you need to use the child manager as explained here http://guides.codepath.com/android/Creating-and-Using-Fragments#nesting-fragments-within-fragments
