### ISSUE TITLE
Nested fragment

### ISSUE THREAD

**Issue by fernandospr** [codepath/android_guides#237]
I was reading https://guides.codepath.com/android/Creating-and-Using-Fragments and I don't agree with this statement (or maybe I misunderstood it?)

> Note that one limitation is that nested (or child) fragments must be dynamically added at runtime to their parent fragment and cannot be statically added using the <fragment> tag.

I have created a test project where a `MainActivity` dynamically adds a `ParentFragment` and this fragment inflates an xml which has several static child fragments using the `<fragment>` tag and it worked ok.

I'm using the following in my build.gradle:
```
minSdkVersion 15
targetSdkVersion 25
com.android.support:appcompat-v7:25.0.1
com.android.support:support-v4:25.0.1
```

I've tested with Genymotion running Android 4.1.1 (API 16).

**Comment by fernandospr** [comment]
Sample project: https://github.com/fernandospr/android-nested-fragments-example

**Comment by nesquena** [comment]
This used to be true for sure https://developer.android.com/about/versions/android-4.2.html#NestedFragments

<img width="945" alt="screen shot 2016-12-03 at 1 39 16 pm" src="https://cloud.githubusercontent.com/assets/6511/20862398/f25759a8-b95d-11e6-9480-7a2994369f29.png">

Can anyone confirm when this change occurred in which nested fragments could be statically inflated?

**Comment by fernandospr** [comment]
I've found out that it doesn't work properly under some situations.
For example, in the `MainActivity` if I want to replace the `ParentFragment` with another `ParentFragment2` **adding to back stack**, e.g.

```
FragmentTransaction ft = getSupportFragmentManager().beginTransaction();
ft.replace(R.id.container, ParentFragment2.newInstance());
ft.addToBackStack(null);
ft.commit();
```

When I press back I get an `IllegalArgumentException`:
```
Caused by: java.lang.IllegalArgumentException: Binary XML file line #11: Duplicate id 0x7f1102c6, tag null, or parent id 0xffffffff with another fragment
```

Removing `addToBackStack` works ok though. I guess it's not fully supported, so the quote:

> Note that one limitation is that nested (or child) fragments must be dynamically added at runtime to their parent fragment and cannot be statically added using the <fragment> tag.

is still true and we should close this issue.

The only way I found to make it work was to remove the `<fragment>` tag and dynamically inflating them.

**Comment by nesquena** [comment]
Okay interesting, thanks for confirming. I never use static nested fragments, so it's hard to say. I always prefer to use them dynamically.
