### ISSUE TITLE
Is it possble to convert MediaRecorder data to byte array or stream? I have seen your codes but couldn't figure it out??

### ISSUE THREAD

**Issue by sulaimansust** [codepath/android_guides#239]
Here is my code, i wanted to work with audio 
        mRecorder = new MediaRecorder();
        mRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
        mRecorder.setOutputFormat(MediaRecorder.OutputFormat.THREE_GPP);
        mRecorder.setOutputFile(mFileName);
        mRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB);

        try {
            mRecorder.prepare();
        } catch (IOException e) {
            Log.e(LOG_TAG, "prepare() failed");
        }
 
        mRecorder.start();

I want my output as a byte array or stream not any file.

**Comment by nasrabadiAM** [comment]
Seems it is possible:
https://stackoverflow.com/a/42750515
