### ISSUE TITLE
Endless scroll for recycler view not working with Nested Scroll View

### ISSUE THREAD

**Issue by ananth10** [codepath/android_guides#248]
I have to implement Endless scroll for recyclerview but i am showing some content above recyclerview , so i have used recyclerview inside nestedscrollview , if i use like this , recyclerview draws all views at first time. so  
endless scroll for calling web service keep on calling. could you suggest me any solution for this?

**Comment by jmitchell38488** [comment]
Do you have example code and an example screenshot? Just a rough UI layout image would be fine.
