### ISSUE TITLE
Camera launch tutorial causes exposedUriException

### ISSUE THREAD

**Issue by DarrienG** [codepath/android_guides#249]
Code is not compliant with API 24+. Anybody who uses it for a reference will face this same error. 

See here: https://inthecheesefactory.com/blog/how-to-share-access-to-file-with-fileprovider-on-android-nougat/en

**Comment by rogerhu** [comment]
Fixed, thanks.   The section was already published [here]( https://github.com/codepath/android_guides/wiki/Sharing-Content-with-Intents#sharing-files-with-api-24-or-higher
) but needed to be referenced in the [camera guide](https://github.com/codepath/android_guides/wiki/Accessing-the-Camera-and-Stored-Media#using-capture-intent).
