### ISSUE TITLE
Dead link in RxJava guide

### ISSUE THREAD

**Issue by santoshag** [codepath/android_guides#251]
The link to retrofit source is a deal link in http://guides.codepath.com/android/RxJava#hot-vs-cold-observables. 
<img width="895" alt="screen shot 2017-01-25 at 11 37 16 am" src="https://cloud.githubusercontent.com/assets/528198/22306067/a76722ca-e2f2-11e6-990e-9ff906f0aeac.png">

**Comment by nesquena** [comment]
I at least fixed the link, @rogerhu can you see if that updated link is still relevant?

**Comment by rogerhu** [comment]
It's still relevant.
