### ISSUE TITLE
Dead link in Managing-Threads-and-Custom-Services

### ISSUE THREAD

**Issue by santoshag** [codepath/android_guides#253]
Dead link in http://guides.codepath.com/android/Managing-Threads-and-Custom-Services#threading-glossary
<img width="903" alt="screen shot 2017-02-14 at 9 10 27 am" src="https://cloud.githubusercontent.com/assets/528198/22940329/5bd04248-f296-11e6-9003-f8ba4ff163c6.png">

**Comment by nesquena** [comment]
Fixed, thanks.
