### ISSUE TITLE
Fragment Navigation Drawer page is missing some content

### ISSUE THREAD

**Issue by tir38** [codepath/android_guides#260]
Most of the content on this page http://guides.codepath.com/android/fragment-navigation-drawer comes from one of the references: http://antonioleiva.com/navigation-view/

However one important step didn't get copied over from reference:

> Our last step will be the Java code. First you need to enable home as up:
>
>        final Toolbar toolbar = (Toolbar) findViewById(R.id.toolbar);
>        setSupportActionBar(toolbar);
>        final ActionBar actionBar = getSupportActionBar();
>
>        if (actionBar != null) {
>            actionBar.setHomeAsUpIndicator(R.drawable.ic_menu_black_24dp);
>            actionBar.setDisplayHomeAsUpEnabled(true);
>        }
>

**Comment by abhivijay96** [comment]
I have tried to add this content, please review it

https://github.com/codepath/android_guides/wiki/Fragment-Navigation-Drawer/_compare/b4b2f41d02942cd5bfa45ed85517b1cf5602714d...e24fe8cb85ebbdc326fe34b2f2778ee2883375de

Thank you

**Comment by nesquena** [comment]
Can someone else confirm this? We run this as a lab and these lines don't aren't generally needed when we run it in the past.

**Comment by tir38** [comment]
looks good @abhivijay96.

@nesquena Without that code, I didn't have an up nav icon to click in the first place.
