### ISSUE TITLE
DialogFragment communicating with target fragment

### ISSUE THREAD

**Issue by tir38** [codepath/android_guides#270]
When dialog fragment communicates with parent (i.e. target) fragment this guide suggests:

https://guides.codepath.com/android/Using-DialogFragment

```
public class EditNameDialogFragment extends DialogFragment {
    // Defines the listener interface
    public interface EditNameDialogListener {
        void onFinishEditDialog(String inputText);
    }

    // Call this method to send the data back to the parent fragment
    public void sendBackResult() {
      // Notice the use of `getTargetFragment` which will be set when the dialog is displayed
      EditNameDialogListener listener = (EditNameDialogListener) getTargetFragment();
      listener.onFinishEditDialog(mEditText.getText().toString());
      dismiss();
    }
}
```

This is a fragile approach for two reasons:
1. unchecked cast
2. parent has to implement interface

Instead this guide should recommend using onActivityResult:

```
public class EditNameDialogFragment extends DialogFragment {

    // Call this method to send the data back to the parent fragment
    public void sendBackResult() {
        // Notice the use of `getTargetFragment` which will be set when the dialog is displayed
        Fragment targetFragment = getTargetFragment();
        if (targetFragment != null) {
            // hosted as dialog by another fragment
            Intent intent = new Intent();
            intent.putExtra("EXTRA_STRING_RESULT", someString);
            targetFragment.onActivityResult(getTargetRequestCode(), Activity.RESULT_OK, intent);
        } else {
            // must be hosted by Activity instead, do something different
            ...
        }
    }
}
```

**Comment by AdamSHurwitz** [comment]
@tir38 Unfortunately `getTargetFragment()` does not work when using the latest Navigation component architecture.

**Comment by safalspiff** [comment]
I have a parentFragment which opens a childFragment1(extends dialog fragment). From childFragment1 again I open another childfragment2(extends dialogFragment) and dismiss the childFragment1.  I want to pass the data to parentFragment from ChildFragment2. 

I tried opening the childfragment one like this by setting the targetFragment as ParentFragment but on doing so there is an error saying that "Setting target fragment to itself create a target cycle""

How do I solve the issue?

**Comment by pitoszud** [comment]
@safall This may happen if you use an extension function e.g run Kotlin standard function. The setTargetFragment function checks whether this scope is a targetFragment, so you cannot use it. Try using let which sends the scope as a parameter, instead of calling on itself.
The reason for checking the target cycle is not clear, but hopefully, Google will address this issue in the future.
