### ISSUE TITLE
Update the section in Beginning Android Resources

### ISSUE THREAD

**Issue by tianzry** [codepath/android_guides#273]
In this [Section](http://guides.codepath.com/android/Beginning-Android-Resources#tutorials), the website [Codelearn](http://codelearn.org/android-tutorial) has been shutdown since late 2015

**Comment by tianzry** [comment]
For more, this section [Organizing your Source Files](http://guides.codepath.com/android/Organizing-your-Source-Files#for-java-codel) ,the website [See this naming guide for more details](https://www.cwu.edu/~gellenbe/javastyle/naming.html) **page not found now**.

**Comment by jsroyal** [comment]
@tianzry Thanks you pointing out issues and reporting.
It will great to update the android guide.
I would request to update the guide and also sending PR for that.
@

**Comment by jsroyal** [comment]
@tianzry Please check now I update page if you can see that.
And close the issue.

**Comment by tianzry** [comment]
@jsroyal well done, everything is fine now.

**Comment by nesquena** [comment]
Thanks!

**Comment by jsroyal** [comment]
@nesquena No thanks, it was just small contribute.
It is honored you have been lots of contributed for a community like me.
Thanks a lot.+1
