### ISSUE TITLE
ARM Translation tools - official page

### ISSUE THREAD

**Issue by kenorb** [codepath/android_guides#283]
Re: [Genymotion 2.0 Emulators with Google Play support](https://github.com/codepath/android_guides/wiki/Genymotion-2.0-Emulators-with-Google-Play-support)

Can you share some official page (or there is any) for any updates of ARM Translation tools in mentioned wiki page?

**Comment by rogerhu** [comment]
The ARM Translation tools you're referring is actually Intel's Houdini project. 

![image](https://user-images.githubusercontent.com/326857/27802904-8e4b3c66-5fdb-11e7-85db-1eeadfe49176.png)

The library itself maps ARM instructions to x86 instructions and somehow was pulled from a working Lenovo laptop but appears to be closed source (https://lists.01.org/pipermail/android-ia/2012-September/000029.html).  

I tried to email one of the lead engineers on the Android-Intel project but the address is bouncing.  If someone can LinkedIn InMail him (https://www.linkedin.com/in/andrew-boie-68360b10/) and/or do further investigation into what happened to this Intel project, that might be a way to get the ball rolling.

**Comment by paulvi** [comment]
https://software.intel.com/en-us/android  

->

https://github.com/projectCeladon

not much active as of 2019
