### ISSUE TITLE
Local Databases with SQLiteOpenHelper - App keeps crashing

### ISSUE THREAD

**Issue by devansh3** [codepath/android_guides#284]
I used your code to create a simple database. However it kept crashing. So I debugged it and it crashed at "db.execSQL(CREATE_Acc_TABLE)"
This is my code:
package com.example.devansh.database;

import android.content.ContentValues;
import android.content.Context;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import android.widget.Toast;

import java.util.ArrayList;
import java.util.List;

import static android.content.ContentValues.TAG;

public class DatabaseHelper extends SQLiteOpenHelper {

    private static final String DATABASE_NAME = "Accel.db";
    private static final int DATABASE_VERSION = 1;

    private static final String TABLE_Acc = "Accelerometer";//Table name

    //Columns name
    private static final String XAxis = "X-Axis";
    private static final String YAxis = "Y-Axis";
    private static final String ZAxis = "Z-Axis";

    private static DatabaseHelper sInstance;

    public static synchronized DatabaseHelper getInstance(Context context) {
        // Use the application context, which will ensure that you
        // don't accidentally leak an Activity's context.
        // See this article for more information: http://bit.ly/6LRzfx
        if (sInstance == null) {
            sInstance = new DatabaseHelper(context.getApplicationContext());
        }
        return sInstance;
    }

    public DatabaseHelper(Context context) {
        super(context, DATABASE_NAME, null, DATABASE_VERSION);
    }

    @Override
    public void onConfigure(SQLiteDatabase db) {
        super.onConfigure(db);
        db.setForeignKeyConstraintsEnabled(true);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        String CREATE_Acc_Table = "CREATE TABLE "
                + TABLE_Acc + "( " + XAxis
                + " INTEGER PRIMARY KEY, " + YAxis
                + " INTEGER, " + ZAxis + " INTEGER);";

        db.execSQL(CREATE_Acc_Table);
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
        if (oldVersion != newVersion) {
            // Simplest implementation is to drop all old tables and recreate them
            db.execSQL("DROP TABLE IF EXISTS " + TABLE_Acc);
            onCreate(db);
        }
    }

    public void addPost() {
        // Create and/or open the database for writing
        SQLiteDatabase db = getWritableDatabase();
        db.beginTransaction();
        try {
            ContentValues values = new ContentValues();
            values.put(XAxis, 1);
            values.put(YAxis, 2);
            values.put(ZAxis, 3);
            db.insertOrThrow(TABLE_Acc, null, values);
            db.setTransactionSuccessful();
        } catch (Exception e) {
            Log.d(TAG, "Error while trying to add post to database");
        } finally {
            db.endTransaction();
        }
    }

    public List<Accelerometer> getAll() {
        List<Accelerometer> Accelerometer = new ArrayList<>();
        String Accelerometer_SELECT_QUERY =
                String.format("SELECT %s FROM %s",
                        XAxis,
                        TABLE_Acc);

        SQLiteDatabase db = getReadableDatabase();
        Cursor cursor = db.rawQuery(Accelerometer_SELECT_QUERY, null);
        try {
            if (cursor.moveToFirst()) {
                do {
                    Accelerometer newUser = new Accelerometer();
                    newUser.xaxis = cursor.getInt(cursor.getColumnIndex(XAxis));
                    Accelerometer.add(newUser);
                } while(cursor.moveToNext());
            }
        } catch (Exception e) {
            Log.d(TAG, "Error while trying to get posts from database");
        } finally {
            if (cursor != null && !cursor.isClosed()) {
                cursor.close();
            }
        }

        return Accelerometer;
    }
}

**Comment by jmitchell38488** [comment]
You _shouldn't_ use dashes `-` in column names, but if you must, you need to make sure that you wrap them in back ticks so that you can use _non-standard naming conventions_ for your columns. You also need to ensure that when you create queries to use the table, those columns are always enclosed by ``` back ticks.

See: https://stackoverflow.com/questions/261455/using-backticks-around-field-names

```sql
CREATE TABLE Accelerometer ( XAxis INTEGER PRIMARY KEY, YAxis INTEGER, ZAxis INTEGER);
```

**Comment by devansh3** [comment]
Thanks a lot. It really helped.
