### ISSUE TITLE
notification channels

### ISSUE THREAD

**Issue by santoshag** [codepath/android_guides#298]
updated the notifications guide to include notification channels introduced in Oreo
https://hackmd.io/s/r1gOQH5GF-

Having trouble including a url link that contains paranthesis, renders fine on macDown

```For API level 26 and above, set a notification channel using updated [NotificationCompat.Builder](https://developer.android.com/reference/android/support/v4/app/NotificationCompat.Builder.html#NotificationCompat.Builder(android.content.Context, java.lang.String)).```

**Comment by nesquena** [comment]
In order to add links with parentheses in markdown you have to put a backslash to escape the parentheses in the URL i.e "\("

**Comment by santoshag** [comment]
it din't work :( 
this might be issue with hackmd, tried another online editor StackEdit. it worked without escaping.

**Comment by nesquena** [comment]
Hmm weird. Thanks for putting this update together

**Comment by santoshag** [comment]
glad to contribute.

**Comment by santoshag** [comment]
removed the part that was causing the issue. 
tried in github editor, it din't help.

**Comment by nesquena** [comment]
@santoshag I reviewed and merged your changes to [notifications](https://github.com/codepath/android_guides/wiki/Notifications) page with some small tweaks. Can you please read through and 1) make sure I didn't miss anything important 2) everything makes sense now on the live page?

Thanks again

**Comment by santoshag** [comment]
Looks good with the tweaks @nesquena, Thanks.
Closing this issue.

**Comment by rogerhu** [comment]
Updated here to start: https://github.com/codepath/android-services-demo/pull/7/files

**Comment by rogerhu** [comment]
I suspect all the labs need to be updated the same too.. :)

**Comment by nesquena** [comment]
Which of the labs use notifications, looks like you are thinking about maps lab? @rogerhu

**Comment by rogerhu** [comment]
Yep, just realized all it needs is a  bump the Parse Android SDK to support Android O.  

https://github.com/parse-community/Parse-SDK-Android/releases/tag/1.16.0

**Comment by nesquena** [comment]
Okay thanks Roger so we should be good then? Anything else that might be broken off the top of your head? I'll also have the instructor and volunteers run through each lab before students this round coming up.
