### ISSUE TITLE
Suggestion - Dagger and Dependency Injection

### ISSUE THREAD

**Issue by polok** [codepath/android_guides#31]
Dependency injection support which is offered by Dagger tool can make our lives more pleasant. Moreover, writing tests is more easier.

I would enjoy contributing to a guide about this. Let me know if you have an interest.

**Comment by IgorGanapolsky** [comment]
I think Dagger2 is the way to go now.  It is vastly simpler than Dagger1.

**Comment by LLin233** [comment]
agree. ButterKnife makes view creating much easier

**Comment by nesquena** [comment]
@vinc3m1 sample project: https://github.com/vinc3m1/nowdothis

**Comment by nesquena** [comment]
Here's a slide deck to link in the guide: https://docs.google.com/presentation/d/1bkctcKjbLlpiI0Nj9v0QpCcNIiZBhVsJsJp1dgU5n98/edit#slide=id.p

**Comment by nesquena** [comment]
Here's the article stub: https://github.com/codepath/android_guides/wiki/Dependency-Injection-with-Dagger

**Comment by nesquena** [comment]
https://github.com/codepath/android_guides/wiki/Reducing-View-Boilerplate-with-Butterknife
