### ISSUE TITLE
AsyncTask for multiple API calls

### ISSUE THREAD

**Issue by pavangayakwad** [codepath/android_guides#314]
Consider I have 5 different API calls to make in a same android Activity and wish to use AsyncTask, should I create 5 different AsyncTask classes for each API call? How to do in the best possible way in this scenario with no much of a code repetition? Pardon me if my question seems stupid, I am a newbie who is exploring Java and Android app development from past few weeks.

**Comment by Truestark** [comment]
Make methods for each API call and call them in doinbackground of one AsyncTask.. simple.

**Comment by pavangayakwad** [comment]
@Truestark how do you manage different types of return values? Can you point me to any sample code?

**Comment by mirzaadil** [comment]
Response received in Jason object and parses in different api

On Jan 12, 2018 12:48 PM, Pavan <notifications@github.com> wrote:

@Truestark<https://github.com/truestark> how do you manage different types of return values? Can you point me to any sample code?

**Comment by pavangayakwad** [comment]
@mirzaadil Thanks for your response. Looks like conceptually I understood your approach and finding it challenging when it comes to blending real-time programming.

Please assist.

Here is my simple AsyncTask code. 

    'private class GetLogTask extends AsyncTask<Object, Void, List<LogRowVM>>{

        @Override
        protected void onPreExecute() {
            super.onPreExecute();
            lst.setVisibility(View.INVISIBLE); //there may different UI control for different API
            prgBar.setVisibility(View.VISIBLE);
        }

        @Override
        protected List<LogRowVM> doInBackground(Object... args) {
            //this logic may different for different API calls 
            String device = (String) args[0];
            Date start = (Date) args[1];
            Date end = (Date) args[2];

            List<LogRowVM> logs = new APIServices().GetLogs(device, start, end);
            if (logs == null) logs = new ArrayList<>();

            return logs;
        }

        @Override
        protected void onPostExecute(List<LogRowVM> logRowVMS) {
            super.onPostExecute(logRowVMS);

           //Logic for PostExecute may be different for different API calls
            lst.setVisibility(View.VISIBLE);
            prgBar.setVisibility(View.INVISIBLE);

            lst.setAdapter(logsAdapter);
            txtCount.setText("Activities: " + logRowVMS.size());
        }
    }

Taking the above code as a reference can you please suggest how can I generalize it for different API calls? The OnPre, doInBackgroun, OnPost execute behave differently for different API calls.

**Comment by pavangayakwad** [comment]
hmm..I think here is the one what wanted 
https://stackoverflow.com/questions/41673318/asynctask-implementation-using-callback-interface-handle-multiple-call-respons

but didn't like the switch case part. Any other better approach?

I was expecting Async and Await (like in javascript or in C#), which are implemented on a method / function level.
