### ISSUE TITLE
Suggestion - Otto

### ISSUE THREAD

**Issue by polok** [codepath/android_guides#32]
If you want to build your apps in way that they have loose coupling between blocks, which could be switched in very easy way you definitely have to read about Otto!.
In short, Otto is an event bus designed to decouple different parts of your application.

I would enjoy contributing to a guide about this. Let me know if you have an interest.

**Comment by nesquena** [comment]
@petzel might be working on a guide for this!

**Comment by rogerhu** [comment]
The limitations and considerations given the lifecycle of fragments/activities documented here would be a big plus here..

**Comment by rogerhu** [comment]
First draft started: https://github.com/codepath/android_guides/wiki/Communicating-with-an-Event-Bus

**Comment by nesquena** [comment]
Looks like a great start @rogerhu, thanks for getting this going
