### ISSUE TITLE
Is there an equivalent of cocoapod for Android for dependency management?

### ISSUE THREAD

**Issue by tonytamsf** [codepath/android_guides#33]
While trying to do both iOS and Android development, I really like Cocoapods for managing dependencies and discover other libraries to use.

Does Android have something similar?

**Comment by ChandrasekarPerumal** [comment]
NEWBIE to react-native as well to mobile app development. 
I'm using Windows 10..

Should I need to install Cocoapods inside React-native appProject/ios folder? If so can you tell me the steps to be done..
