### ISSUE TITLE
A best code for getting location when app is in background and foreground for Pie devices 

### ISSUE THREAD

**Issue by BlackBlind567** [codepath/android_guides#360]
I know [here](https://github.com/codepath/android_guides/issues/220) is a good example of background services to get location. But in that code I am unable to understand that which one service is best of getting location and how to get location on another activity from service. I also know i have to call start service in another activity and i have to write broadcast function for getting location periodically.

Now my main problem is I only know all of that what I have to do but here I am unable how to do .

I want a specific code help where I have a service for location and get that location on another activity when app is in background or foreground with less battery drag for **Pie** **Devices.**

**Comment by BlackBlind567** [comment]
I know it was late but you can find best code [here](https://github.com/BlackBlind567/Location_Updates-Background_Foreground/tree/master) 
Now I solved my problem with my patience.]
Thank You 

Any One want to location updation fork or download my repo

**Comment by hafiz013** [comment]
@BlackBlind567  did u code working fine in background and foreground process?

**Comment by BlackBlind567** [comment]
> @BlackBlind567 did u code working fine in background and foreground process?

yes, it's working. Did you try my code?

**Comment by hafiz013** [comment]
@BlackBlind567  yes can but after long time (a few hours) it is close because battery optimiser by manufacture itself.
