### ISSUE TITLE
How to load into ImageCardView

### ISSUE THREAD

**Issue by AR-code-99** [codepath/android_guides#366]
I want to load an image into an ImageCardView object

    override fun onBindViewHolder(viewHolder: Presenter.ViewHolder, item: Any) {
        val cardView = viewHolder.view as ImageCardView

...
            Picasso.with(viewHolder.view.context)
                .load(movie.thumb)
                .into(cardView)

When I try this I get

None of the following functions can be called with the arguments supplied:
public open fun into(p0: ImageView!): Unit defined in com.squareup.picasso.RequestCreator
public open fun into(p0: Target!): Unit defined in com.squareup.picasso.RequestCreator

How do I load an image into ImageCardView?  Thanks

**Comment by ConstantinKV** [comment]
https://www.javatips.net/api/TuentiTV-master/app/src/main/java/com/github/pedrovgs/tuentitv/ui/picasso/PicassoImageCardViewTarget.java

**Comment by AR-code-99** [comment]
Thank you ConstantinKV.  That worked for me.

I'm using Kotlin so here is what my code looked like.

    override fun onBindViewHolder(viewHolder: Presenter.ViewHolder, item: Any) {
    ...
        val mTarget = PicassoImageCardViewTarget(cardView)
        Picasso.with(cardView.context)
           .load(movie.thumb)
           .into(mTarget)
  }
    class PicassoImageCardViewTarget(private val mImageCardView: ImageCardView) : Target {
        override fun onBitmapLoaded(bitmap: Bitmap, loadedFrom: Picasso.LoadedFrom) {
            val bitmapDrawable = BitmapDrawable(mImageCardView.context.resources, bitmap)
            mImageCardView.mainImage = bitmapDrawable
        }

        override fun onBitmapFailed(drawable: Drawable?) {
            mImageCardView.mainImage = drawable
        }

        override fun onPrepareLoad(drawable: Drawable?) {
            // Do nothing, default_background manager has its own transitions
        }
    }

**Comment by AR-code-99** [comment]
Also if anyone is interested you can accomplish the same thing with AsyncTask.

    override fun onBindViewHolder(viewHolder: Presenter.ViewHolder, item: Any?) {
        val movie = item as Movie
        var cardView = viewHolder.view as ImageCardView

        Log.d(TAG, "onBindViewHolder")
        cardView.titleText = movie.title
        cardView.contentText = movie.studio
        cardView.setMainImageDimensions(CARD_WIDTH, CARD_HEIGHT)
        DownloadImage(cardView).execute(movie.cardImageUrl)
    }

    class DownloadImage( private val imageCardView: ImageCardView ) : AsyncTask<String, Int, Bitmap?> () {
        // this is the old school way of downloading images asynchronously
        override fun doInBackground(vararg p0: String?): Bitmap? {
            Log.d(TAG, "doInBackground Called")
            val url = URL(p0[0])
            val urlConnection = url.openConnection() as HttpURLConnection
            var bitmap: Bitmap? = null

            try {
                val inputStream = BufferedInputStream(urlConnection.inputStream)
                bitmap = BitmapFactory.decodeStream(inputStream)
            } catch (e: IOException) {
                e.printStackTrace()
            } finally {
                urlConnection.disconnect()
            }
            return bitmap
        }

        override fun onPostExecute(result: Bitmap?) {
            super.onPostExecute(result)
            imageCardView.mainImage = BitmapDrawable(result)
        }
    }
