### ISSUE TITLE
Gradle 2.0 Released

### ISSUE THREAD

**Issue by whoshuu** [codepath/android_guides#39]
The announcement can be found [here](http://forums.gradle.org/gradle/topics/gradle_2_0_released).

We should update the gradle [guide](https://github.com/thecodepath/android_guides/wiki/Getting-Started-with-Gradle) as soon as possible.

**Comment by rogerhu** [comment]
Gradle 2.0 is already being used in this guide (see `distributionUrl=http\://services.gradle.org/distributions/gradle-2.21-all.zip`.  

The Android Gradle plugin, which actual does all the dirty work of creating the final APK package, has been updated to 1.2.3.  1.3.0 is in beta: http://tools.android.com/tech-docs/new-build-system
