### ISSUE TITLE
Managing Threads and Custom Services page disappeared.

### ISSUE THREAD

**Issue by PavelVinnik** [codepath/android_guides#407]
On 02.18 it was accessible and on 02.21 it is not.

**Comment by jclement92** [comment]
Hi @PavelVinnik, found the guide on an internet archive site. Here it is:

https://web.archive.org/web/20201130162203/https://guides.codepath.com/android/managing-threads-and-custom-services

**Comment by nesquena** [comment]
Thanks for flagging this, I've restored the page now on the wiki as well https://github.com/codepath/android_guides/wiki/Managing-Threads-and-Custom-Services

**Comment by LarssonTech2** [comment]
Thank you for the link, have a great day.
