### ISSUE TITLE
Obfuscation code and ProGuard

### ISSUE THREAD

**Issue by AlexeyTaran** [codepath/android_guides#46]
I found some sources about ProGuard and obfuscation in general
- http://developer.android.com/intl/ru/tools/help/proguard.html
- http://www.crashlytics.com/blog/mastering-proguard-for-building-lightweight-android-code/

**Comment by nesquena** [comment]
@rogerhu started this guide here https://github.com/codepath/android_guides/wiki/Configuring-ProGuard. Thanks!
