### ISSUE TITLE
Suggestion - DBFlow 

### ISSUE THREAD

**Issue by agrosner** [codepath/android_guides#64]
https://github.com/Raizlabs/DBFlow
A blazing fast, powerful, and very simple ORM android database library that writes database code for you.

**Comment by nesquena** [comment]
https://github.com/Raizlabs/DBFlow :+1: would be great to have a guide for this

**Comment by lduparc** [comment]
https://github.com/Raizlabs/DBFlow :+1: would be great to have a guide for this

**Comment by rogerhu** [comment]
Started here: https://github.com/codepath/android_guides/wiki/DBFlow-Guide

**Comment by nesquena** [comment]
Sweet! Thanks
