### ISSUE TITLE
Edited the Networking Guide

### ISSUE THREAD

**Issue by aneeshjoshi** [codepath/android_guides#67]
Hi Nathan,

Didn't realize that a pull request doesn't get automatically generated. I updated the doc to close the input stream in a finally block instead. Apologies.  Please review and close this issue if the change is acceptable.

https://github.com/codepath/android_guides/wiki/Sending-and-Managing-Network-Requests/cc4b07b95e1826a1d0512c905c6f91992b62c3c2

**Comment by nesquena** [comment]
Thanks
