### ISSUE TITLE
Suggestion - Iconify

### ISSUE THREAD

**Issue by jeroenkruis** [codepath/android_guides#68]
Suggestion for adding [Iconify](https://github.com/JoanZapata/android-iconify) to the Must Have Libraries section. It allows you to add [font-awesome](http://fortawesome.github.io/Font-Awesome/) icons to your Android project.

**Comment by aphexcx** [comment]
This is another great icon site for material design
http://materialdesignicons.com/

**Comment by nesquena** [comment]
Added Iconify to the must have libraries https://github.com/codepath/android_guides/wiki/Must-Have-Libraries#ui-components. Also added the material design icons to a few places. Thanks!
