### ISSUE TITLE
link Setting up Android Studio is invalid

### ISSUE THREAD

**Issue by audiebantzhan** [codepath/android_guides#70]

**Comment by nesquena** [comment]
Which link?

**Comment by audiebantzhan** [comment]
#### Getting Started

* [Setting up Android Studio](http://goo.gl/X2SVFR)

**Comment by nesquena** [comment]
What error do you get when you click? That's a public link. Try it in incognito mode. It's more likely your organization disallows you to view google drive presentations from outside your org.

**Comment by audiebantzhan** [comment]
Thanks for your explanation, I get it ！
