### ISSUE TITLE
UI Testing with Espresso

### ISSUE THREAD

**Issue by appoll** [codepath/android_guides#72]
I have been interacting with this "small, predictable and easy to learn" API for the past weeks and would like to share some of the aspects I've learned about it. 
Would it make any sense to invest my time in this? The original documentation is pretty vast and covers most of the possible use cases, also providing some samples.
I would happily wrap something up, only if truly needed.

**Comment by nesquena** [comment]
Yes, I think it would be greatly appreciated. The vastness is good but it's too thorough. A "cliffnotes" version of this would be greatly appreciated. A solid primer on Espresso is sorely missing.

See: https://github.com/codepath/android_guides/wiki/Contributing-Guidelines

Please feel free to start it as a gist or a markdown text file and share when ready. See [this guide](http://guides.codepath.com/android/Android-Unit-and-Integration-testing) as a reference but feel free to add it as a new guide instead.

**Comment by nesquena** [comment]
See #34 as well (this is technically a dup so I am going to close)
