### ISSUE TITLE
Use starter project for Robolectric setup

### ISSUE THREAD

**Issue by shurane** [codepath/android_guides#75]
It's probably worth mentioning about [robolectric/deckard-gradle](https://github.com/robolectric/deckard-gradle) starter project in the [wiki page about robolectric unit-testing](https://github.com/codepath/android_guides/wiki/Robolectric-Installation-for-Unit-Testing).

It's all set up to run JUnit tests, so that's pretty nifty. I'm not sure how the edit on that wiki should be made though, hence making an issue instead of a PR.

**Comment by rogerhu** [comment]
You should be able to click the Edit page on the right?

The guide did mention https://github.com/robolectric/deckard-gradle as a README.  I've found Roboelectric 3.0 to be easier and needs fewer excludes, which that repo is still using 2.4.

Also, I've found that https://github.com/mutexkid/android-studio-robolectric-example was a bit more helpful in light of Roboelectric 3.0 and Android Gradle plugin supporting stuff.  I've updated the Wiki just now to avoid some of the cumbersome steps needed to run these tests inside Android Studio.

**Comment by rogerhu** [comment]
@shurane can you take a look at the changes and let me know what you think?

**Comment by rogerhu** [comment]
https://github.com/robolectric/deckard-gradle is still on Roboelectric 2.4 so closing for now.  Hopefully the guide is enough.

**Comment by shurane** [comment]
Oh I just saw this now, sorry about that. Yeah, it doesn't look like deckard-gradle gets much love. Ah well. I haven't used the mutexkid example but I'll try it out.
