### ISSUE TITLE
Android M Content

### ISSUE THREAD

**Issue by nesquena** [codepath/android_guides#78]
Prepare an action plan for which guides need to be added or updated accordingly.

  - http://android-developers.blogspot.com/2015/05/android-m-developer-preview-tools.html
  - http://developer.android.com/preview/api-overview.html
  - http://android-developers.blogspot.com/2015/05/android-design-support-library.html
  - http://developer.android.com/tools/support-library/index.html
  - http://android-developers.blogspot.com/2015/05/a-closer-look-at-google-play-services-75.html
  - http://developer.android.com/preview/overview.html
  - http://www.google.com/design/icons/
  - http://hmkcode.com/material-design-app-android-design-support-library-appcompat/
  - https://www.bignerdranch.com/blog/becoming-material-with-android-design-support-library/

Sample code [can be found here with cheesesquare](https://github.com/chrisbanes/cheesesquare)

Setup: `compile 'com.android.support:design:22.2.0'`

Key new topics:

 - [Android design support library](http://android-developers.blogspot.com/2015/05/android-design-support-library.html) (FAB, Navigation Drawer, TabLayout, SnackBar)
 - New [Play Services Updates](http://android-developers.blogspot.com/2015/05/a-closer-look-at-google-play-services-75.html)

Guides to be added or updated:

- [x] [Floating Action Buttons](https://github.com/codepath/android_guides/wiki/Floating-Action-Buttons) - See [the FloatingActionButton design widget](http://developer.android.com/reference/android/support/design/widget/FloatingActionButton.html)
- [x] Use [TabLayout](http://developer.android.com/reference/android/support/design/widget/TabLayout.html) to wrap view pager. Update: [SlidingTabLayout](https://github.com/codepath/android_guides/wiki/Google-Play-Style-Tabs-using-TabLayout) guide, [ViewPager guide](https://github.com/codepath/android_guides/wiki/ViewPager-with-FragmentPagerAdapter#tabbed-interface-with-pager)
- [x] [Snackbar](https://github.com/codepath/android_guides/wiki/Displaying-the-Snackbar) - Shown on the bottom of the screen and contain text with an optional single action. Create a guide on these.
- [x] [Navigation Drawer](https://github.com/codepath/android_guides/wiki/Fragment-Navigation-Drawer) - [NavigationView](http://developer.android.com/reference/android/support/design/widget/NavigationView.html) and [See Here](http://android-developers.blogspot.com/2015/05/android-design-support-library.html)
- [x] [AppCompatActivity](https://plus.google.com/+AndroidDevelopers/posts/LNyDnnBYJ8r) needs to replace `ActionBarActivity` and bump support version in gradle to `com.android.support:appcompat-v7:22.2.0`.
- [x] [EditText](https://github.com/codepath/android_guides/wiki/Working-with-the-EditText#displaying-floating-label-feedback) - [Floating Label](http://www.google.com/design/spec/components/text-fields.html#text-fields-floating-labels) with [TextInputLayout](http://developer.android.com/reference/android/support/design/widget/TextInputLayout.html)

Additional new features:

- [x] [AppBarLayout](http://developer.android.com/reference/android/support/design/widget/AppBarLayout.html) and [CollapsingToolbarLayout](http://developer.android.com/reference/android/support/design/widget/CollapsingToolbarLayout.html)
- [x] Permissions are now granular ([Link](http://developer.android.com/preview/features/runtime-permissions.html), [Samples](https://github.com/googlesamples/android-RuntimePermissions))
- [x] [CoordinatorLayout](http://developer.android.com/reference/android/support/design/widget/CoordinatorLayout.html) ([Guide](https://github.com/codepath/android_guides/wiki/Handling-Scrolls-with-CoordinatorLayout))
- [x] [GCM](https://developers.google.com/cloud-messaging/android/start)
- [ ] Better app linking with `autoVerify` ([Link](http://developer.android.com/preview/features/app-linking.html))
- [ ] UI Performance ([Link](http://developer.android.com/preview/testing/performance.html))
- [ ] [Data Binding Layout Templates](https://developer.android.com/tools/data-binding/guide.html#data_binding_layout_files)
- [x] Espresso Testing

**Comment by rogerhu** [comment]
Also new TabLayout for ViewPager (http://developer.android.com/reference/android/support/design/widget/TabLayout.html)

**Comment by rogerhu** [comment]
Oh Google..the support library doesn't even compile because their docs are typed wrong.

https://code.google.com/p/android/issues/detail?id=175066

```
Instead
com.android.support:support-design:22.0.0
sholud be:
com.android.support:design:22.2.0
```

**Comment by rogerhu** [comment]
Floating action button guide updated - let me know your thoughts.  I'm going to update the lab.

https://github.com/codepath/android_guides/wiki/Floating-Action-Buttons#googles-official-support-library

**Comment by rogerhu** [comment]
Example/demo code for snackbars, CoordinatorLayout, TabLayout all here: https://github.com/chrisbanes/cheesesquare

**Comment by nesquena** [comment]
The floating action button updates looks great @rogerhu thanks! Glad to see the demos linked as well. Hoping we can create a guide for the new TabLayout and any other key features soon.

**Comment by nesquena** [comment]
Compiled all the Android M features above that we need to update in our guides. Most important is rewriting the navigation drawer guide and updating our tabs guide with TabLayout.

**Comment by rogerhu** [comment]
Created a separate guide for the support design library: https://github.com/codepath/android_guides/wiki/Support-Design-Library

I renamed the Google Play Sliding TabLayout to https://github.com/codepath/android_guides/wiki/Google-Play-Style-Tabs-using-TabLayout.  It looks like SlidingTabLayout simply got moved to be an inner class of TabLayout.

**Comment by nesquena** [comment]
@rogerhu Awesome, added a list of "features" to the support design library. The updates to Tabs guide look great. It's nice that the guide just required some modifications on the existing guide and they maintained the same interface.

**Comment by rogerhu** [comment]
The NavigationView changes look fairly straightforward -- here is what I think has to happen for https://github.com/codepath/android_guides/wiki/Fragment-Navigation-Drawer.

1. I think we can kill the ListView `lvDrawer` and `NavDrawerListAdapter`, along with the XML layout.
2. Add NavigationView according to https://github.com/chrisbanes/cheesesquare/blob/master/app/src/main/res/layout/activity_main.xml#L27-L34.
3. Add menu/nav_drawer.xml according to https://github.com/chrisbanes/cheesesquare/blob/master/app/src/main/res/menu/drawer_view.xml
4. Add layout/nav_header.xml according to 
https://github.com/chrisbanes/cheesesquare/blob/master/app/src/main/res/layout/nav_header.xml.
5. Change FragmentNavigationDrawer so it doesn't need items #1.
https://gist.github.com/nidhi1608/104b31cb0ebc1f7b3f69

**Comment by nesquena** [comment]
I created the snackbar guide here: https://github.com/codepath/android_guides/wiki/Displaying-the-Snackbar

**Comment by nesquena** [comment]
@rogerhu Yep, you've sized up the changes that need to be made well for the drawer guide, thanks. Great additions so far with tabs and FAB.

**Comment by nesquena** [comment]
We need to address #79 re tablayout and custom tabs

**Comment by rogerhu** [comment]
Fixed https://github.com/codepath/android_guides/issues/79.

**Comment by nesquena** [comment]
Nice! you are quick @rogerhu

**Comment by rogerhu** [comment]
First pass at https://github.com/codepath/android_guides/wiki/Fragment-Navigation-Drawer.  I got rid of the whole FragmentNavigationDrawer and put all the stuff in the code.

**Comment by nesquena** [comment]
@rogerhu Nice glad we can get rid of the custom class. @nidhi1608 can you take a look through this and let Roger know if there's any feedback.

**Comment by nidhi1608** [comment]
Great job @rogerhu. I am so glad to see `FragmentNavigationDrawer` go. Although it provided a really nice abstraction to the underlying code, students didn't always think it was trivial to understand. 

It might be useful to mention the optional `app:headerLayout` attribute of the `NavigationView` to provide header layout. (Similar to play store)

`NavigationView` takes care of the scrim protection of the status bar for you, ensuring that your NavigationView interacts with the status bar appropriately on API 21+ devices. So I am not sure if we still need Toolbar to do this magic for API 21+. 

Guide explains selecting an item through code, which is great. It might also be useful to mention that menu items can be selected through xml using `android:checked="true"` attribute.

The last thing to add to the guide is the support for subheaders to separate [groups of items](http://developer.android.com/guide/topics/ui/menus.html#groups) right into xml. We can get rid of [detailed navigation drawer tutorial]() link after adding this to the guide.

```xml
<item
    android:id="@+id/navigation_subheader"
    android:title="@string/navigation_subheader">
    <menu>
        <item
            android:id="@+id/navigation_sub_item_1"
            android:icon="@drawable/ic_android"
            android:title="@string/navigation_sub_item_1"/>
        <item
            android:id="@+id/navigation_sub_item_2"
            android:icon="@drawable/ic_android"
            android:title="@string/navigation_sub_item_2"/>
    </menu>
</item>
```

**Comment by rogerhu** [comment]
Also should add gcm for iOS - and possibly a gae backend to make it easier to showcase how it works

**Comment by rogerhu** [comment]
Also thiszis cool but beta https://developer.android.com/tools/data-binding/guide.html#data_binding_layout_files

**Comment by nesquena** [comment]
Nice, very cool data binding framework, we will definitely need a guide for that eventually, thanks for the link.

**Comment by rogerhu** [comment]
@nidhi1608 - I tried without Toolbar but the navigation drawer shows up under the ActionBar.  Part of me thinks is that not much work has been done to support it with this AppCompat library.  The demo code is also usiing ToolBar.

Added `app:headerLayout`, added `android:checked="true"` and added subheaders. 

Also fixed the translucent stuff too by forcing the walkthrough to use a Material Design theme.

**Comment by nesquena** [comment]
Added floating labels feature to [edittext guide](https://github.com/codepath/android_guides/wiki/Working-with-the-EditText#displaying-floating-label-feedback). Let me know what you think.

**Comment by jaytolentino** [comment]
hello! :smiley_cat:  so looks like a bunch of things in GCM are now deprecated, including `GoogleCloudMessaging.register()` (see [here](https://developers.google.com/android/reference/com/google/android/gms/gcm/GoogleCloudMessaging#register(java.lang.String...))) and instead there are now [tokens](https://developers.google.com/cloud-messaging/android/client#sample-register). i see GCM is listed in this issue so just wanted to give you guys a heads up!

**Comment by nesquena** [comment]
@jaytolentino thanks for pointing this out, hope one of us will have the bandwidth to update the [GCM guide](https://github.com/codepath/android_guides/wiki/Google-Cloud-Messaging) soon.

**Comment by rogerhu** [comment]
Will take a look after I check out the Retrofit issue..

**Comment by nesquena** [comment]
@jaytolentino ... looks like roger has updated the GCM guide in record time along with retrofit. Can you take a look and give us any feedback?

**Comment by nesquena** [comment]
Roger is still working on the token piece actually to replace register although updated a first pass so the guide works properly again (still using deprecated register for now)

**Comment by rogerhu** [comment]
I updated for now the register() stuff: https://gist.github.com/rogerhu/dfdf83c58e7022839256/revisions

The recommended approach is to use IntentServices instead of AsyncTask.  This way you can reuse the code that handles registration.  Will update later.

**Comment by jaytolentino** [comment]
@nesquena sure I'll take a look! Thanks @rogerhu :clap: :clap:

**Comment by sibeliusseraphini** [comment]
[PermissionDispatcher](https://github.com/hotchemi/PermissionsDispatcher) makes simple to handle Android M through annotations

**Comment by nesquena** [comment]
@sibeliusseraphini [Guide here now for PermissionsDispatcher](http://guides.codepath.com/android/Managing-Runtime-Permissions-with-PermissionsDispatcher)

**Comment by nesquena** [comment]
The vast majority of topics have now been added (thanks primarily to @rogerhu). The following items have been added as separate issues:

 * [Better app linking](https://github.com/codepath/android_guides/issues/156)
 * [Data binding library](https://github.com/codepath/android_guides/issues/175)

Closing this now finally.
