### ISSUE TITLE
TabLayout  setCustomTabView doesn't exist

### ISSUE THREAD

**Issue by twilly86** [codepath/android_guides#79]
On this article...

https://github.com/codepath/android_guides/wiki/Google-Play-Style-Tabs-using-TabLayout

tabLayout.setCustomTabView  does not exist

**Comment by nesquena** [comment]
Thanks for the report @twilly86.

@rogerhu Since there's no such thing as `setCustomTabView`, what's the equivalent solution for this section? https://github.com/codepath/android_guides/wiki/Google-Play-Style-Tabs-using-TabLayout#add-icons-to-tablayout

**Comment by twilly86** [comment]
I came up with this work around.  You basically get each tab after they are generated, then set the customview on each tab.  Not the greatest.

       int tabCount = tabLayout.getTabCount();
        for(int i = 0; i < tabCount; i++){
            TabLayout.Tab tab = tabLayout.getTabAt(i);
            tab.setCustomView(R.layout.custom_tab);
            tab.setText(i);
        }

This also resets the text, so you need to set it again.

**Comment by nesquena** [comment]
Definitely not ideal but looking at [TabLayout](https://android.googlesource.com/platform/frameworks/support.git/+/master/design/src/android/support/design/widget/TabLayout.java) source, I don't know if I see another way...

**Comment by twilly86** [comment]
Where do we submit bugs for this library?  When I set a style on this xml tag, it removes the indicator.

    <android.support.design.widget.TabLayout
        android:id="@+id/tabs"
        style="@style/MyCustomTabLayout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content" />

**Comment by rogerhu** [comment]
I don't think you even need to go down the custom layout route because the ```  <item name="textAllCaps">true</item>``` can be overriden as a style.

https://android.googlesource.com/platform/frameworks/support.git/+/master/design/res/values/styles.xml

Will update if this is correct.

**Comment by rogerhu** [comment]
Updated: https://github.com/codepath/android_guides/wiki/Google-Play-Style-Tabs-using-TabLayout#add-icons-to-tablayout now.

There's some centering issues with icons + text but someone else can help find a work on a way to help fine-tune it. :)

**Comment by nesquena** [comment]
@twilly86 would you be able to confirm?

**Comment by nesquena** [comment]
https://github.com/codepath/android_guides/wiki/Google-Play-Style-Tabs-using-TabLayout#add-custom-view-to-tablayout
