### ISSUE TITLE
Handling Scrolls with CoordinatorLayout

### ISSUE THREAD

**Issue by nesquena** [codepath/android_guides#80]
Building off of #78, we need guides for coordinating using the new `CoordinatorLayout`: 

- [x] Scrolling up or down the floating action button slides up and down (See [guide](https://github.com/codepath/android_guides/wiki/Floating-Action-Buttons#animating-the-floating-action-button))
- [x] [CoordinatorLayout](http://developer.android.com/reference/android/support/design/widget/CoordinatorLayout.html) - a layout which provides an additional level of control over touch events between child views
   - A great use of this is when you add a `FloatingActionButton` as a child of your `CoordinatorLayout` and then pass that `CoordinatorLayout` to your `Snackbar.make()` call - instead of the snackbar displaying over the floating action button, the FloatingActionButton takes advantage of additional callbacks provided by `CoordinatorLayout` to automatically move upward as the snackbar animates in and returns to its position when the snackbar animates out
   - `CoordinatorLayout` also provides an `layout_anchor` attribute which, along with `layout_anchorGravity`, can be used to place floating views, such as the FloatingActionButton, relative to other views.
- [x] [AppBarLayout](http://developer.android.com/reference/android/support/design/widget/AppBarLayout.html) - allows your Toolbar and other views (such as tabs provided by TabLayout) to react to scroll events in a sibling view marked with a ScrollingViewBehavior
   - `app:layout_behavior` and `app:layout_scrollFlags`
- [x] [CollapsingToolbarLayout](http://developer.android.com/reference/android/support/design/widget/CollapsingToolbarLayout.html)  
  - Affords detailed control on how different elements react to collapsing
  - `CollapsingToolbarLayout’s app:layout_collapseMode="pin"`
  - `app:layout_collapseMode="parallax"` and `app:layout_collapseParallaxMultiplier="0.7"`
  - `app:contentScrim="?attr/colorPrimary" `
- [x] Setup ToolBar to show and hide as you scroll. 
- [x] Header of the list docks to top of the screen

References:

- <http://hmkcode.com/material-design-app-android-design-support-library-appcompat/>
- <http://blog.grafixartist.com/toolbar-animation-with-android-design-support-library/>
- <https://github.com/chrisbanes/cheesesquare>
- <https://www.bignerdranch.com/blog/becoming-material-with-android-design-support-library/>

**Comment by rogerhu** [comment]
Funny, it just got committed 2 days ago:

https://plus.google.com/+IanLake/posts/Pxx1srKMVqi
https://github.com/ianhanniballake/cheesesquare/commit/aefa8b57e61266e4ad51bef36e669d69f7fd749c

**Comment by nesquena** [comment]
Nice reference! I'd want to produce this in a guide form too. It's such a common effect, I get asked by engineers how to do this a lot.

**Comment by rogerhu** [comment]
FYI -- CoordinatorLayout only works with RecyclerView, not ListView.    I'm in the process of trying to figure out how this works.

https://plus.google.com/101784949561498190574/posts/KPbsTY4NANx

**Comment by nesquena** [comment]
Thanks for the update. This is an interesting a tutorial: http://hmkcode.com/material-design-app-android-design-support-library-appcompat/ (see coordinator section). A guide on how to get coordinatorlayout working along with [AppBarLayout](http://developer.android.com/reference/android/support/design/widget/AppBarLayout.html) and [CollapsingToolbarLayout](http://developer.android.com/reference/android/support/design/widget/CollapsingToolbarLayout.html) would be really useful.

**Comment by rogerhu** [comment]
Yeah my problem is that they don't explain what's going on...Apparently there are pre-defined Behavior's (Floating Action Button Bars know how to deal with Snackbars in the default FloatingActionBehavior) and the code examples all presume you use AppBarLayout.. forking https://android.googlesource.com/platform/frameworks/support.git/ seems to show that we're missing a bunch of files that would normally tell us how this all works.  Fortunately Android Studio uses IntelliJ 13 and supports decompiling Java classes now...otherwise it would be a complete mystery.

**Comment by nesquena** [comment]
I agree this is all totally under explained which is odd and there's no good explanation anywhere.

**Comment by rogerhu** [comment]
CoordinatorLayout with FAB described here -- https://github.com/codepath/android_guides/wiki/Floating-Action-Buttons#animating-the-floating-action-button

**Comment by rogerhu** [comment]
Started guide here:

https://github.com/codepath/android_guides/wiki/Handling-Scrolls-with-CoordinatorLayout

**Comment by rogerhu** [comment]
Started guide here:

https://github.com/codepath/android_guides/wiki/Handling-Scrolls-with-CoordinatorLayout

Will add AppBarLayout and stuff soon.

**Comment by rogerhu** [comment]
Started guide here:

https://github.com/codepath/android_guides/wiki/Handling-Scrolls-with-CoordinatorLayout

Will add AppBarLayout and stuff soon.

**Comment by rogerhu** [comment]
Started guide here:

https://github.com/codepath/android_guides/wiki/Handling-Scrolls-with-CoordinatorLayout

Will add AppBarLayout and stuff soon.

**Comment by nesquena** [comment]
This looks like a great start to the handling scrolls guide, thanks!

**Comment by rogerhu** [comment]
Second pass updated.

**Comment by nesquena** [comment]
This looks awesome Roger. Seriously thanks for putting all this together!

**Comment by rogerhu** [comment]
[CoordinatorLayout with Floating Action Buttons](https://github.com/codepath/android_guides/wiki/Floating-Action-Buttons#using-coordinatorlayout
) just got 10x more easier with show() and hide() methods that handle the fade-in/fade out effects instead of [reimplementing the animation  code](
https://github.com/codepath/android_guides/wiki/Floating-Action-Buttons/_compare/1a81765bcfa4f76755140cef5be1d42eee714b24...d1c4a994faeb79b358727c416500ca18d0eb006b).

**Comment by nesquena** [comment]
Sweet!

**Comment by skytoo** [comment]
Great.

**Comment by nesquena** [comment]
Going to close this, done for now.

**Comment by mansukhgagal** [comment]
I found one nice library  try it... http://stackoverflow.com/a/34947835/4395114 thanks @Henry Tao

**Comment by rogerhu** [comment]
Didn't the issue get fixed? (https://code.google.com/p/android/issues/detail?id=177729)  And given that Google wants these bugs filed (b.android.com), why not doing so instead of needing to fork?
