### ISSUE TITLE
Keeping the Navigation Drawer State when navigating to and from other activities

### ISSUE THREAD

**Issue by surfer190** [codepath/android_guides#84]
There is no information about keeping the Navigation Drawer State when navigating to and from other activities. Ie. moving from activity to activity with Navigation Drawer.

[Navigation Drawer](https://github.com/codepath/android_guides/wiki/Fragment-Navigation-Drawer)

**Comment by rogerhu** [comment]
Nav drawers are primarily used to swap fragments in and out within an Activity.    What is your use case?

**Comment by surfer190** [comment]
Managed to sort it out, by adding the position as an extra to the intent.

```
int position = getIntent().getIntExtra("position", 0);
        if (position != 0){
            //coming from an activity
            selectDrawer(position);
        }
```

There are several cases:
* Detail view
* Settings
* Results

Seems acceptable but surely there is a `savedState` we can go back to.

**Comment by surfer190** [comment]
@rogerhu
Say we have a `main menu` fragment which loaded first for users to pick what they want to do.

I have a callback which is changing to the correct title but not the correct selected item.

```
PopupMenu p  = new PopupMenu(getApplicationContext(), null);
        Menu menu = p.getMenu();

        getMenuInflater().inflate(R.menu.nav_drawer_menu, menu);
        
        int drawerId = 0;
        switch (pos){
            case 0: drawerId = R.id.nav_first_fragment;
                    break;
            case 1: drawerId = R.id.nav_second_fragment;
                    break;
            case 2: drawerId = R.id.nav_third_fragment;
                    break;
            case 3: drawerId = R.id.nav_fourth_fragment;
                    break;
            case 4: drawerId = R.id.nav_fifth_fragment;
                    break;
            case 5: drawerId = R.id.nav_sixth_fragment;
                    break;
            case 6: drawerId = R.id.nav_seventh_fragment;
                break;
        }
        MenuItem item = menu.findItem(drawerId);
        selectDrawerItem(item);
```

This is not working cause I am not actually getting the reference to the actual `MenuItem`

**Comment by surfer190** [comment]
@rogerhu Sorted out the above issue using:

```
MenuItem item = mNavigationView.getMenu().findItem(drawerId);
        selectDrawerItem(item);
```

However the intent back to the navigation drawer activity has an issue that when orientation changes it executes `onCreate` and defaults to showing a specific fragment.

**Comment by rogerhu** [comment]
Could you store it as a sharedpreferences instead? http://guides.codepath.com/android/Storing-and-Accessing-SharedPreferences
