### ISSUE TITLE
Add maps utils library to the must have list.

### ISSUE THREAD

**Issue by appoll** [codepath/android_guides#85]
Under heavy development, but ready to be used.
https://github.com/googlemaps/android-maps-utils
spoiler here: https://www.youtube.com/watch?v=nb2X9IjjZpM

**Comment by rogerhu** [comment]
Yeah I've used it.  You know you can add it directly to the guides... :)

**Comment by appoll** [comment]
I would have done it but to be honest had no idea under which category. 
Left the tough decisions for the touch guys. :smile:

**Comment by nesquena** [comment]
Added here: https://github.com/codepath/android_guides/wiki/Google-Maps-API-v2-Usage#utility-library
