### ISSUE TITLE
nothing is happening with my drawer when I click an Item to navigate

### ISSUE THREAD

**Issue by aoiserizawa** [codepath/android_guides#87]
I tried to make a fragment and made a drawer here is my code:

import android.support.v4.app.FragmentManager;
import android.support.v4.app.Fragment;
import android.content.res.Configuration;
import android.support.design.widget.Snackbar;
import android.support.v4.widget.DrawerLayout;
import android.support.v7.app.ActionBarDrawerToggle;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.view.Menu;
import android.view.MenuItem;
import android.support.v7.widget.Toolbar;
import android.support.design.widget.NavigationView;
import android.view.View;
import android.widget.LinearLayout;
import android.widget.RelativeLayout;

public class MainActivity extends AppCompatActivity implements View.OnClickListener, NavigationView.OnNavigationItemSelectedListener{
    private Toolbar mToolBar;
    private NavigationView mDrawer;
    private ActionBarDrawerToggle mdrawerToggle;
    private DrawerLayout mDrawerLayout;

    private RelativeLayout digitalFrontier;
    private RelativeLayout forwardThinkers;
    private RelativeLayout preferedActions;

    private LinearLayout innerParent;

    public String viewVar;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        initViews();

        digitalFrontier.setOnClickListener(this);
        forwardThinkers.setOnClickListener(this);
        preferedActions.setOnClickListener(this);
    }

    @Override
    public boolean onCreateOptionsMenu(Menu menu) {
        // Inflate the menu; this adds items to the action bar if it is present.
        getMenuInflater().inflate(R.menu.menu_main, menu);
        return true;
    }

    @Override
    public boolean onOptionsItemSelected(MenuItem item) {
        // Handle action bar item clicks here. The action bar will
        // automatically handle clicks on the Home/Up button, so long
        // as you specify a parent activity in AndroidManifest.xml.
        int id = item.getItemId();

        //noinspection SimplifiableIfStatement
        if (id == R.id.action_settings) {
            return true;
        }

        return super.onOptionsItemSelected(item);
    }

    @Override
    public void onConfigurationChanged(Configuration newConfig) {
        super.onConfigurationChanged(newConfig);

        mdrawerToggle.onConfigurationChanged(newConfig);
    }

    private void initViews(){
        mToolBar = (Toolbar) findViewById(R.id.app_bar);
        setSupportActionBar(mToolBar);
        mDrawer = (NavigationView) findViewById(R.id.main_drawer);
        mDrawerLayout = (DrawerLayout) findViewById(R.id.drawer_parent);
        mdrawerToggle = new ActionBarDrawerToggle(
                this,
                mDrawerLayout,
                mToolBar,
                R.string.drawer_open,
                R.string.drawer_close);

        mDrawerLayout.setDrawerListener(mdrawerToggle);
        // indicator based on whether the drawerlayout is in open or closed
        mdrawerToggle.syncState();

        digitalFrontier = (RelativeLayout) findViewById(R.id.digital_frontier);
        forwardThinkers = (RelativeLayout) findViewById(R.id.forward_thinkers);
        preferedActions = (RelativeLayout) findViewById(R.id.prefered_actions);

        innerParent = (LinearLayout) findViewById(R.id.inner_parent);

        mDrawer.setNavigationItemSelectedListener(this);

    }

    @Override
    public void onClick(View v) {

        if(v.getId() == R.id.digital_frontier || v.getId() == R.id.forward_thinkers ||
                v.getId() == R.id.prefered_actions ){

            detailActivity(v);
        }

    }

    private void detailActivity(View view){

        switch (view.getId()){
            case R.id.digital_frontier:
                viewVar = "digital frontier";
                break;
            case R.id.forward_thinkers:
                viewVar = "forward thinkers";
                break;
            case R.id.prefered_actions:

                viewVar = "prefered actions";
                break;
        }

        Snackbar.make(mDrawerLayout, viewVar , Snackbar.LENGTH_LONG).show();
    }

    @Override
    public boolean onNavigationItemSelected(MenuItem menuItem) {
        selectDrawerItem(menuItem);
        return false;
    }

    public void selectDrawerItem(MenuItem menuItem) {
        // Create a new fragment and specify the planet to show based on
        // position
        Fragment fragment = null;

        Class fragmentClass = null;
        switch(menuItem.getItemId()) {
            case R.id.agency_menu_item:
                fragmentClass = FragmentAgency.class;
                break;
        }

        try {
            fragment = (Fragment) fragmentClass.newInstance();
        } catch (Exception e) {
            e.printStackTrace();
        }

        // Insert the fragment by replacing any existing fragment
        FragmentManager fragmentManager = this.getSupportFragmentManager();
        fragmentManager.beginTransaction().replace(R.id.fragment_content, fragment).commit();

        // Highlight the selected item, update the title, and close the drawer
        menuItem.setChecked(true);
        setTitle(menuItem.getTitle());
        //mDrawer.closeDrawers();
    }
}

//activity_main.xml
<android.support.v4.widget.DrawerLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    android:id="@+id/drawer_parent"
    tools:context=".MainActivity">

    <LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="vertical"
        android:id="@+id/inner_parent">

        <include android:id="@+id/app_bar" layout="@layout/app_bar" />

        <fragment
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:name="com.serverus.oom.FragmentHome"
            android:id="@+id/fragment_content" />

    </LinearLayout>

    <android.support.design.widget.NavigationView
        android:id="@+id/main_drawer"
        android:layout_width="wrap_content"
        android:layout_height="match_parent"
        android:layout_gravity="start"
        app:menu="@menu/menu_drawer"
        />

</android.support.v4.widget.DrawerLayout>

//FragmentHome.java

import android.os.Bundle;
import android.support.v4.app.Fragment;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

public class FragmentHome extends Fragment {

    public FragmentHome() {
        // Required empty public constructor
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment
        return inflater.inflate(R.layout.fragment_home, container, false);
    }

}

but then when I tried clicking the Item Agency on my drawer nothing happens not even errors. 
please help guys. Im just new in android and java. TIA

**Comment by rachid804** [comment]
I Quickly checked your code it sames that you are confusing using fragment in xml and pragmatically:
In your Layout instead of using <fragment ... /> use FrameLayout as a container:
If you follow this guide you will get correctly https://guides.codepath.com/android/Fragment-Navigation-Drawer

**Comment by aoiserizawa** [comment]
@rachid804 thanks for that one and I made it working by changing the Fragment to FrameLayout to make it change. My problem now is how to make the user go back from the previous fragments

**Comment by kareemzok** [comment]
Hello, 

I got the same problem suddenly, I have try all possible solutions offered from StackOverflow such as adding the listener, checking the layout but nothing works while it was working before. 
It happened few days ago. 
Any idea or advice please, we are stuck!

**Comment by gagangamer** [comment]
> I Quickly checked your code it sames that you are confusing using fragment in xml and pragmatically:
> In your Layout instead of using <fragment ... /> use FrameLayout as a container:
> If you follow this guide you will get correctly https://guides.codepath.com/android/Fragment-Navigation-Drawer

thanks bro
