### ISSUE TITLE
Retrofit

### ISSUE THREAD

**Issue by PrathameshKesarkar** [codepath/android_guides#89]
The example in Retrofit is not working anymore even the description is not that explanatory

**Comment by rogerhu** [comment]
Can you take a look again?  I've bumped the versions and revised the guides.

**Comment by PrathameshKesarkar** [comment]
Now it is fine I have another Link which is pretty simple to follow here's it 
 
http://themakeinfo.com/2015/04/android-retrofit-images-tutorial/

**Comment by nesquena** [comment]
I added that link to references at bottom of page. Thanks for the link.
