### ISSUE TITLE
RecyclerView setOnclick outside the adapter

### ISSUE THREAD

**Issue by PrathameshKesarkar** [codepath/android_guides#90]
the contents of the recyclerview is pretty much good however there is one minor detail you missed out it is how can we hadle click in outside the adapter from Fragments or Activity can u add a snippet on it 

Here's a good ref : http://stackoverflow.com/questions/24471109/recyclerview-onclick/26196831#26196831

**Comment by nesquena** [comment]
Scroll to the second half of this section http://guides.codepath.com/android/Using-the-RecyclerView#attaching-click-handlers-to-items which I believe covers a good approach for this using listeners.
