### ISSUE TITLE
PercentRelativeLayout

### ISSUE THREAD

**Issue by nesquena** [codepath/android_guides#91]
@rogerhu did a start here https://github.com/codepath/android_guides/wiki/Design-Support-Library#sample-code setting up a link but we should put together a guide for PercentRelativeLayout or mention in our [existing layouts](http://guides.codepath.com/android/Constructing-View-Layouts) guide as well. See [this sample code](https://github.com/JulienGenoud/android-percent-support-lib-sample) for a good starting point.

**Comment by rogerhu** [comment]
https://github.com/codepath/android_guides/wiki/Constructing-View-Layouts#percentrelativelayout

**Comment by nesquena** [comment]
Nice, looks great. I think we can close this now
