### ISSUE TITLE
Add uses-Permission vs Permissions

### ISSUE THREAD

**Issue by singhajay7** [codepath/android_guides#92]

**Comment by pranaypatel512** [comment]
User Permission:-
-------------------------
Requests a permission that the application must be granted in order for it to operate correctly. Permissions are granted by the user when the application is installed, not while it's running. 
http://developer.android.com/guide/topics/manifest/uses-permission-element.html

Permission:-
-------------------------
Declares a security permission that can be used to limit access to specific components or features of this or other applications. See the Permissions section in the introduction, and the Security and Permissions document for more information on how permissions work.
http://developer.android.com/guide/topics/manifest/permission-element.html
