### ISSUE TITLE
Start Android Development - Easy Instructions

### ISSUE THREAD

**Issue by manoj77** [codepath/android_guides#94]
I have read about <a href="https://github.com/codepath/android_guides/wiki/Beginning-Android-Resources">Beginning Android Resources</a> and found it useful for android developers. Here is an another informative video tutorial on getting started with android development at http://findnerd.com/list/view/Getting-started-with-android/3570/, hope this will help developer. Apart from this mobile devs can surf this <a href="http://findnerd.com/askquestion/android">android developer forum</a> to look for quality content related to questions and answers on android development.

**Comment by nambv** [comment]
thank you so much for your will!

**Comment by nesquena** [comment]
Thanks will add your links to the beginning guides!

**Comment by manoj77** [comment]
You are welcome and hope you will find more useful content here.
