### ISSUE TITLE
Implementing a Horizontal ListView Guide

### ISSUE THREAD

**Issue by mhqasrawi** [codepath/android_guides#96]
you can <h5>Implement a Horizontal ListView</h5> without a third library , now there's a <b>Recycler View </b>which you can attach a <b>Horizontal Layout manager</b> to it and so its a horizontal listview without using any third library ..

**Comment by nesquena** [comment]
Yes that article needs to be updated, TwoWayView is RecyclerView made a bit simpler to use for the horizontal case: https://github.com/lucasr/twoway-view. We also have a [RecyclerView guide](http://guides.codepath.com/android/Using-the-RecyclerView) as well.
