### ISSUE TITLE
Contacts with RecyclerView?

### ISSUE THREAD

**Issue by brunerson** [codepath/android_guides#98]
Hey! I've been looking around for an easy way to display a contact list with a RecyclerView since it doesn't work with a SimpleCursorAdapter. You use a ListView here: https://guides.codepath.com/android/Loading-Contacts-with-Content-Providers. Any ideas?

**Comment by rogerhu** [comment]
Interesting question..

http://stackoverflow.com/questions/26517855/using-the-recyclerview-with-a-database

Can you use a combination of https://guides.codepath.com/android/Using-the-RecyclerView and https://guides.codepath.com/android/Populating-a-ListView-with-a-CursorAdapter to accomplish this goal?

**Comment by nesquena** [comment]
@brunerson did you figure this out, any interest in adding a section to our recyclerview guide on this?
