### ISSUE TITLE
Suggestion: Add More Images/Screenshots to "Defining The ActionBar"

### ISSUE THREAD

**Issue by JeffreyCA** [codepath/android_guides#99]
[This page](https://github.com/codepath/android_guides/wiki/Defining-The-ActionBar) could use a bit more visual content.

Can you add a screenshot as an example to show the Action Items on the ActionBar [here](https://github.com/codepath/android_guides/wiki/Defining-The-ActionBar#adding-action-items)?

**Comment by nesquena** [comment]
Yes, you are right, there should be more screenshots on this page.
